// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EmailsInitParameters struct {
}

type EmailsObservation struct {

	// (String)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean)
	Verified *bool `json:"verified,omitempty" tf:"verified,omitempty"`
}

type EmailsParameters struct {
}

type GpgKeyInitParameters struct {

	// (String) Armored GPG public key. Changing this forces a new resource to be created.
	// Armored GPG public key. Changing this forces a new resource to be created.
	ArmoredPublicKey *string `json:"armoredPublicKey,omitempty" tf:"armored_public_key,omitempty"`
}

type GpgKeyObservation struct {

	// (String) Armored GPG public key. Changing this forces a new resource to be created.
	// Armored GPG public key. Changing this forces a new resource to be created.
	ArmoredPublicKey *string `json:"armoredPublicKey,omitempty" tf:"armored_public_key,omitempty"`

	// (Boolean) Can this key certify.
	// Can this key certify.
	CanCertify *bool `json:"canCertify,omitempty" tf:"can_certify,omitempty"`

	// (Boolean) Can this key encrypt communications.
	// Can this key encrypt communications.
	CanEncryptComms *bool `json:"canEncryptComms,omitempty" tf:"can_encrypt_comms,omitempty"`

	// (Boolean) Can this key encrypt storage.
	// Can this key encrypt storage.
	CanEncryptStorage *bool `json:"canEncryptStorage,omitempty" tf:"can_encrypt_storage,omitempty"`

	// (Boolean) Can this key sign.
	// Can this key sign.
	CanSign *bool `json:"canSign,omitempty" tf:"can_sign,omitempty"`

	// (String) Time at which the GPG key was created.
	// Time at which the GPG key was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (List of Object) Emails associated with the GPG key. (see below for nested schema)
	// Emails associated with the GPG key.
	Emails []EmailsObservation `json:"emails,omitempty" tf:"emails,omitempty"`

	// (String) Time at which the GPG key expires.
	// Time at which the GPG key expires.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (Number) Numeric identifier of the GPG key.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the GPG key.
	// ID of the GPG key.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) Primary ID of the GPG key.
	// Primary ID of the GPG key.
	PrimaryKeyID *string `json:"primaryKeyId,omitempty" tf:"primary_key_id,omitempty"`

	// (String) The public key.
	// The public key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (List of Object) Subkeys of the GPG key. (see below for nested schema)
	// Subkeys of the GPG key.
	Subkeys []SubkeysObservation `json:"subkeys,omitempty" tf:"subkeys,omitempty"`
}

type GpgKeyParameters struct {

	// (String) Armored GPG public key. Changing this forces a new resource to be created.
	// Armored GPG public key. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	ArmoredPublicKey *string `json:"armoredPublicKey,omitempty" tf:"armored_public_key,omitempty"`
}

type SubkeysInitParameters struct {
}

type SubkeysObservation struct {

	// (Boolean) Can this key certify.
	CanCertify *bool `json:"canCertify,omitempty" tf:"can_certify,omitempty"`

	// (Boolean) Can this key encrypt communications.
	CanEncryptComms *bool `json:"canEncryptComms,omitempty" tf:"can_encrypt_comms,omitempty"`

	// (Boolean) Can this key encrypt storage.
	CanEncryptStorage *bool `json:"canEncryptStorage,omitempty" tf:"can_encrypt_storage,omitempty"`

	// (Boolean) Can this key sign.
	CanSign *bool `json:"canSign,omitempty" tf:"can_sign,omitempty"`

	// (String) Time at which the GPG key was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Time at which the GPG key expires.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// (Number) Numeric identifier of the GPG key.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the GPG key.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) Primary ID of the GPG key.
	PrimaryKeyID *string `json:"primaryKeyId,omitempty" tf:"primary_key_id,omitempty"`

	// (String) The public key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`
}

type SubkeysParameters struct {
}

// GpgKeySpec defines the desired state of GpgKey
type GpgKeySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   GpgKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GpgKeyInitParameters `json:"initProvider,omitempty"`
}

// GpgKeyStatus defines the observed state of GpgKey.
type GpgKeyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GpgKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GpgKey is the Schema for the GpgKeys API. Forgejo user GPG key resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type GpgKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.armoredPublicKey) || (has(self.initProvider) && has(self.initProvider.armoredPublicKey))",message="spec.forProvider.armoredPublicKey is a required parameter"
	Spec   GpgKeySpec   `json:"spec"`
	Status GpgKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GpgKeyList contains a list of GpgKeys
type GpgKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GpgKey `json:"items"`
}

// Repository type metadata.
var (
	GpgKey_Kind             = "GpgKey"
	GpgKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GpgKey_Kind}.String()
	GpgKey_KindAPIVersion   = GpgKey_Kind + "." + CRDGroupVersion.String()
	GpgKey_GroupVersionKind = CRDGroupVersion.WithKind(GpgKey_Kind)
)

func init() {
	SchemeBuilder.Register(&GpgKey{}, &GpgKeyList{})
}
