// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *BranchProtection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Collaborator) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DeployKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GpgKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Organization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationActionSecret) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationActionVariable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PersonalAccessToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryActionSecret) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryActionVariable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryWebhook) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SshKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Team) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
