// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationActionSecretInitParameters struct {

	// (String, Sensitive) Data of the secret.
	// Data of the secret.
	DataSecretRef v2.SecretKeySelector `json:"dataSecretRef" tf:"-"`

	// (String) Name of the secret. Changing this forces a new resource to be created.
	// Name of the secret. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type OrganizationActionSecretObservation struct {

	// (String) Time at which the secret was created.
	// Time at which the secret was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the secret. Changing this forces a new resource to be created.
	// Name of the secret. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type OrganizationActionSecretParameters struct {

	// (String, Sensitive) Data of the secret.
	// Data of the secret.
	// +kubebuilder:validation:Optional
	DataSecretRef v2.SecretKeySelector `json:"dataSecretRef" tf:"-"`

	// (String) Name of the secret. Changing this forces a new resource to be created.
	// Name of the secret. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	// +kubebuilder:validation:Optional
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

// OrganizationActionSecretSpec defines the desired state of OrganizationActionSecret
type OrganizationActionSecretSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrganizationActionSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationActionSecretInitParameters `json:"initProvider,omitempty"`
}

// OrganizationActionSecretStatus defines the observed state of OrganizationActionSecret.
type OrganizationActionSecretStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationActionSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationActionSecret is the Schema for the OrganizationActionSecrets API. Forgejo organization action secret resource. Note: The authenticated user must be a member of the managed organization(s) or have administrative privileges!
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type OrganizationActionSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataSecretRef)",message="spec.forProvider.dataSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationActionSecretSpec   `json:"spec"`
	Status OrganizationActionSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationActionSecretList contains a list of OrganizationActionSecrets
type OrganizationActionSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationActionSecret `json:"items"`
}

// Repository type metadata.
var (
	OrganizationActionSecret_Kind             = "OrganizationActionSecret"
	OrganizationActionSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationActionSecret_Kind}.String()
	OrganizationActionSecret_KindAPIVersion   = OrganizationActionSecret_Kind + "." + CRDGroupVersion.String()
	OrganizationActionSecret_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationActionSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationActionSecret{}, &OrganizationActionSecretList{})
}
