// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PersonalAccessTokenInitParameters struct {

	// (String) Name of the personal access token. Changing this forces a new resource to be created.
	// Name of the personal access token. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Scopes of the personal access token. Changing this forces a new resource to be created.
	// Scopes of the personal access token. Changing this forces a new resource to be created.
	// +listType=set
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.User
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.Reference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.Selector `json:"userSelector,omitempty" tf:"-"`
}

type PersonalAccessTokenObservation struct {

	// (Number) Numeric identifier of the personal access token.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the personal access token. Changing this forces a new resource to be created.
	// Name of the personal access token. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Scopes of the personal access token. Changing this forces a new resource to be created.
	// Scopes of the personal access token. Changing this forces a new resource to be created.
	// +listType=set
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) Last eight characters of the personal access token.
	// Last eight characters of the personal access token.
	TokenLastEight *string `json:"tokenLastEight,omitempty" tf:"token_last_eight,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type PersonalAccessTokenParameters struct {

	// (String) Name of the personal access token. Changing this forces a new resource to be created.
	// Name of the personal access token. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Scopes of the personal access token. Changing this forces a new resource to be created.
	// Scopes of the personal access token. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	// +listType=set
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.User
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.Reference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.Selector `json:"userSelector,omitempty" tf:"-"`
}

// PersonalAccessTokenSpec defines the desired state of PersonalAccessToken
type PersonalAccessTokenSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PersonalAccessTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PersonalAccessTokenInitParameters `json:"initProvider,omitempty"`
}

// PersonalAccessTokenStatus defines the observed state of PersonalAccessToken.
type PersonalAccessTokenStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PersonalAccessTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PersonalAccessToken is the Schema for the PersonalAccessTokens API. Forgejo personal access token resource. Note: Due to an upstream limitation, one cannot create access tokens when authorized with access tokens. Use basic-auth instead.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type PersonalAccessToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scopes) || (has(self.initProvider) && has(self.initProvider.scopes))",message="spec.forProvider.scopes is a required parameter"
	Spec   PersonalAccessTokenSpec   `json:"spec"`
	Status PersonalAccessTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PersonalAccessTokenList contains a list of PersonalAccessTokens
type PersonalAccessTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PersonalAccessToken `json:"items"`
}

// Repository type metadata.
var (
	PersonalAccessToken_Kind             = "PersonalAccessToken"
	PersonalAccessToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PersonalAccessToken_Kind}.String()
	PersonalAccessToken_KindAPIVersion   = PersonalAccessToken_Kind + "." + CRDGroupVersion.String()
	PersonalAccessToken_GroupVersionKind = CRDGroupVersion.WithKind(PersonalAccessToken_Kind)
)

func init() {
	SchemeBuilder.Register(&PersonalAccessToken{}, &PersonalAccessTokenList{})
}
