// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ExternalTrackerInitParameters struct {

	// (String) External issue tracker URL format. Use the placeholders {user}, {repo} and {index} for the username, repository name and issue index.
	// External issue tracker URL format. Use the placeholders `{user}`, `{repo}` and `{index}` for the username, repository name and issue index.
	ExternalTrackerFormat *string `json:"externalTrackerFormat,omitempty" tf:"external_tracker_format,omitempty"`

	// (String) External issue tracker issue regular expression.
	// External issue tracker issue regular expression.
	ExternalTrackerRegexpPattern *string `json:"externalTrackerRegexpPattern,omitempty" tf:"external_tracker_regexp_pattern,omitempty"`

	// (String) External issue tracker number format.
	// External issue tracker number format.
	ExternalTrackerStyle *string `json:"externalTrackerStyle,omitempty" tf:"external_tracker_style,omitempty"`

	// (String) URL of external issue tracker.
	// URL of external issue tracker.
	ExternalTrackerURL *string `json:"externalTrackerUrl,omitempty" tf:"external_tracker_url,omitempty"`
}

type ExternalTrackerObservation struct {

	// (String) External issue tracker URL format. Use the placeholders {user}, {repo} and {index} for the username, repository name and issue index.
	// External issue tracker URL format. Use the placeholders `{user}`, `{repo}` and `{index}` for the username, repository name and issue index.
	ExternalTrackerFormat *string `json:"externalTrackerFormat,omitempty" tf:"external_tracker_format,omitempty"`

	// (String) External issue tracker issue regular expression.
	// External issue tracker issue regular expression.
	ExternalTrackerRegexpPattern *string `json:"externalTrackerRegexpPattern,omitempty" tf:"external_tracker_regexp_pattern,omitempty"`

	// (String) External issue tracker number format.
	// External issue tracker number format.
	ExternalTrackerStyle *string `json:"externalTrackerStyle,omitempty" tf:"external_tracker_style,omitempty"`

	// (String) URL of external issue tracker.
	// URL of external issue tracker.
	ExternalTrackerURL *string `json:"externalTrackerUrl,omitempty" tf:"external_tracker_url,omitempty"`
}

type ExternalTrackerParameters struct {

	// (String) External issue tracker URL format. Use the placeholders {user}, {repo} and {index} for the username, repository name and issue index.
	// External issue tracker URL format. Use the placeholders `{user}`, `{repo}` and `{index}` for the username, repository name and issue index.
	// +kubebuilder:validation:Optional
	ExternalTrackerFormat *string `json:"externalTrackerFormat" tf:"external_tracker_format,omitempty"`

	// (String) External issue tracker issue regular expression.
	// External issue tracker issue regular expression.
	// +kubebuilder:validation:Optional
	ExternalTrackerRegexpPattern *string `json:"externalTrackerRegexpPattern,omitempty" tf:"external_tracker_regexp_pattern,omitempty"`

	// (String) External issue tracker number format.
	// External issue tracker number format.
	// +kubebuilder:validation:Optional
	ExternalTrackerStyle *string `json:"externalTrackerStyle,omitempty" tf:"external_tracker_style,omitempty"`

	// (String) URL of external issue tracker.
	// URL of external issue tracker.
	// +kubebuilder:validation:Optional
	ExternalTrackerURL *string `json:"externalTrackerUrl" tf:"external_tracker_url,omitempty"`
}

type ExternalWikiInitParameters struct {

	// (String) URL of external wiki.
	// URL of external wiki.
	ExternalWikiURL *string `json:"externalWikiUrl,omitempty" tf:"external_wiki_url,omitempty"`
}

type ExternalWikiObservation struct {

	// (String) URL of external wiki.
	// URL of external wiki.
	ExternalWikiURL *string `json:"externalWikiUrl,omitempty" tf:"external_wiki_url,omitempty"`
}

type ExternalWikiParameters struct {

	// (String) URL of external wiki.
	// URL of external wiki.
	// +kubebuilder:validation:Optional
	ExternalWikiURL *string `json:"externalWikiUrl" tf:"external_wiki_url,omitempty"`
}

type InternalTrackerInitParameters struct {

	// (Boolean) Let only contributors track time?
	// Let only contributors track time?
	AllowOnlyContributorsToTrackTime *bool `json:"allowOnlyContributorsToTrackTime,omitempty" tf:"allow_only_contributors_to_track_time,omitempty"`

	// (Boolean) Enable dependencies for issues and pull requests?
	// Enable dependencies for issues and pull requests?
	EnableIssueDependencies *bool `json:"enableIssueDependencies,omitempty" tf:"enable_issue_dependencies,omitempty"`

	// (Boolean) Enable time tracking?
	// Enable time tracking?
	EnableTimeTracker *bool `json:"enableTimeTracker,omitempty" tf:"enable_time_tracker,omitempty"`
}

type InternalTrackerObservation struct {

	// (Boolean) Let only contributors track time?
	// Let only contributors track time?
	AllowOnlyContributorsToTrackTime *bool `json:"allowOnlyContributorsToTrackTime,omitempty" tf:"allow_only_contributors_to_track_time,omitempty"`

	// (Boolean) Enable dependencies for issues and pull requests?
	// Enable dependencies for issues and pull requests?
	EnableIssueDependencies *bool `json:"enableIssueDependencies,omitempty" tf:"enable_issue_dependencies,omitempty"`

	// (Boolean) Enable time tracking?
	// Enable time tracking?
	EnableTimeTracker *bool `json:"enableTimeTracker,omitempty" tf:"enable_time_tracker,omitempty"`
}

type InternalTrackerParameters struct {

	// (Boolean) Let only contributors track time?
	// Let only contributors track time?
	// +kubebuilder:validation:Optional
	AllowOnlyContributorsToTrackTime *bool `json:"allowOnlyContributorsToTrackTime,omitempty" tf:"allow_only_contributors_to_track_time,omitempty"`

	// (Boolean) Enable dependencies for issues and pull requests?
	// Enable dependencies for issues and pull requests?
	// +kubebuilder:validation:Optional
	EnableIssueDependencies *bool `json:"enableIssueDependencies,omitempty" tf:"enable_issue_dependencies,omitempty"`

	// (Boolean) Enable time tracking?
	// Enable time tracking?
	// +kubebuilder:validation:Optional
	EnableTimeTracker *bool `json:"enableTimeTracker,omitempty" tf:"enable_time_tracker,omitempty"`
}

type PermissionsInitParameters struct {
}

type PermissionsObservation struct {

	// (Boolean) Allowed to administer?
	// Allowed to administer?
	Admin *bool `json:"admin,omitempty" tf:"admin,omitempty"`

	// (Boolean) Allowed to pull?
	// Allowed to pull?
	Pull *bool `json:"pull,omitempty" tf:"pull,omitempty"`

	// (Boolean) Allowed to push?
	// Allowed to push?
	Push *bool `json:"push,omitempty" tf:"push,omitempty"`
}

type PermissionsParameters struct {
}

type RepositoryInitParameters struct {

	// forward-only merge pull requests? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to fast-forward-only merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowFastForwardOnlyMerge *bool `json:"allowFastForwardOnlyMerge,omitempty" tf:"allow_fast_forward_only_merge,omitempty"`

	// (Boolean) Allowed to manually merge pull requests? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to manually merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowManualMerge *bool `json:"allowManualMerge,omitempty" tf:"allow_manual_merge,omitempty"`

	// (Boolean) Allowed to create merge commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowMergeCommits *bool `json:"allowMergeCommits,omitempty" tf:"allow_merge_commits,omitempty"`

	// forward? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to rebase then fast-forward? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowRebase *bool `json:"allowRebase,omitempty" tf:"allow_rebase,omitempty"`

	// (Boolean) Allowed to rebase then create merge commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to rebase then create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowRebaseExplicit *bool `json:"allowRebaseExplicit,omitempty" tf:"allow_rebase_explicit,omitempty"`

	// (Boolean) Allowed to update pull request branch by rebase? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to update pull request branch by rebase? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowRebaseUpdate *bool `json:"allowRebaseUpdate,omitempty" tf:"allow_rebase_update,omitempty"`

	// (Boolean) Allowed to create squash commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to create squash commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowSquashMerge *bool `json:"allowSquashMerge,omitempty" tf:"allow_squash_merge,omitempty"`

	// (Boolean) Archive the repo instead of delete?
	// Archive the repo instead of delete?
	ArchiveOnDestroy *bool `json:"archiveOnDestroy,omitempty" tf:"archive_on_destroy,omitempty"`

	// (Boolean) Is the repository archived?
	// Is the repository archived?
	Archived *bool `json:"archived,omitempty" tf:"archived,omitempty"`

	// (String, Sensitive) API token for authenticating with migrate / clone URL. Note: This setting is only effective if clone_addr is set.
	// API token for authenticating with migrate / clone URL. **Note**: This setting is only effective if `clone_addr` is set.
	AuthTokenSecretRef *v2.SecretKeySelector `json:"authTokenSecretRef,omitempty" tf:"-"`

	// intialized? Changing this forces a new resource to be created.
	// Whether the repository should be auto-intialized? Changing this forces a new resource to be created.
	AutoInit *bool `json:"autoInit,omitempty" tf:"auto_init,omitempty"`

	// detect manual pull request merges? Note: This setting is only effective if has_pull_requests is true.
	// Auto-detect manual pull request merges? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AutodetectManualMerge *bool `json:"autodetectManualMerge,omitempty" tf:"autodetect_manual_merge,omitempty"`

	// (String) Migrate / clone from URL. Changing this forces a new resource to be created.
	// Migrate / clone from URL. Changing this forces a new resource to be created.
	CloneAddr *string `json:"cloneAddr,omitempty" tf:"clone_addr,omitempty"`

	// (Boolean) Allow maintainer edits on pull requests by default? Note: This setting is only effective if has_pull_requests is true.
	// Allow maintainer edits on pull requests by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultAllowMaintainerEdit *bool `json:"defaultAllowMaintainerEdit,omitempty" tf:"default_allow_maintainer_edit,omitempty"`

	// (String) Default branch of the repository.
	// Default branch of the repository.
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// (Boolean) Delete pull request branch after merge by default? Note: This setting is only effective if has_pull_requests is true.
	// Delete pull request branch after merge by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultDeleteBranchAfterMerge *bool `json:"defaultDeleteBranchAfterMerge,omitempty" tf:"default_delete_branch_after_merge,omitempty"`

	// (String) Default merge style of the repository. Note: This setting is only effective if has_pull_requests is true.
	// Default merge style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultMergeStyle *string `json:"defaultMergeStyle,omitempty" tf:"default_merge_style,omitempty"`

	// (String) Default pull request update style of the repository. Note: This setting is only effective if has_pull_requests is true.
	// Default pull request update style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultUpdateStyle *string `json:"defaultUpdateStyle,omitempty" tf:"default_update_style,omitempty"`

	// (String) Description of the repository.
	// Description of the repository.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// tracking references when mirroring? Note: This setting is only effective if mirror is true.
	// Remove obsolete remote-tracking references when mirroring? **Note**: This setting is only effective if `mirror` is `true`.
	EnablePrune *bool `json:"enablePrune,omitempty" tf:"enable_prune,omitempty"`

	// (Attributes) Settings for external issue tracker. Note: This setting is only effective if has_issues is true. (see below for nested schema)
	ExternalTracker *ExternalTrackerInitParameters `json:"externalTracker,omitempty" tf:"external_tracker,omitempty"`

	// (Attributes) Settings for external wiki. Note: This setting is only effective if has_wiki is true. (see below for nested schema)
	ExternalWiki *ExternalWikiInitParameters `json:"externalWiki,omitempty" tf:"external_wiki,omitempty"`

	// (String) Gitignores to use. Changing this forces a new resource to be created.
	// Gitignores to use. Changing this forces a new resource to be created.
	Gitignores *string `json:"gitignores,omitempty" tf:"gitignores,omitempty"`

	// (Boolean) Is the repository wiki globally editable? Note: This setting is only effective if has_wiki is true.
	// Is the repository wiki globally editable? **Note**: This setting is only effective if `has_wiki` is `true`.
	GloballyEditableWiki *bool `json:"globallyEditableWiki,omitempty" tf:"globally_editable_wiki,omitempty"`

	// (Boolean) Are integrated CI/CD pipelines enabled?
	// Are integrated CI/CD pipelines enabled?
	HasActions *bool `json:"hasActions,omitempty" tf:"has_actions,omitempty"`

	// (Boolean) Is the repository issue tracker enabled?
	// Is the repository issue tracker enabled?
	HasIssues *bool `json:"hasIssues,omitempty" tf:"has_issues,omitempty"`

	// (Boolean) Is the repository package registry enabled?
	// Is the repository package registry enabled?
	HasPackages *bool `json:"hasPackages,omitempty" tf:"has_packages,omitempty"`

	// (Boolean) Are repository projects enabled?
	// Are repository projects enabled?
	HasProjects *bool `json:"hasProjects,omitempty" tf:"has_projects,omitempty"`

	// (Boolean) Are repository pull requests enabled?
	// Are repository pull requests enabled?
	HasPullRequests *bool `json:"hasPullRequests,omitempty" tf:"has_pull_requests,omitempty"`

	// (Boolean) Are repository releases enabled?
	// Are repository releases enabled?
	HasReleases *bool `json:"hasReleases,omitempty" tf:"has_releases,omitempty"`

	// (Boolean) Is the repository wiki enabled?
	// Is the repository wiki enabled?
	HasWiki *bool `json:"hasWiki,omitempty" tf:"has_wiki,omitempty"`

	// (Boolean) Are whitespace conflicts ignored? Note: This setting is only effective if has_pull_requests is true.
	// Are whitespace conflicts ignored? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	IgnoreWhitespaceConflicts *bool `json:"ignoreWhitespaceConflicts,omitempty" tf:"ignore_whitespace_conflicts,omitempty"`

	// in issue tracker. Note: This setting is only effective if has_issues is true. (see below for nested schema)
	InternalTracker *InternalTrackerInitParameters `json:"internalTracker,omitempty" tf:"internal_tracker,omitempty"`

	// (String) Issue Label set to use. Changing this forces a new resource to be created.
	// Issue Label set to use. Changing this forces a new resource to be created.
	IssueLabels *string `json:"issueLabels,omitempty" tf:"issue_labels,omitempty"`

	// (Boolean) Whether to migrate labels. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate labels. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Labels *bool `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Boolean) Whether to migrate LFS files. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate LFS files. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Lfs *bool `json:"lfs,omitempty" tf:"lfs,omitempty"`

	// (String) LFS endpoint to use. Changing this forces a new resource to be created. Note: This setting is only effective if lfs is true.
	// LFS endpoint to use. Changing this forces a new resource to be created. **Note**: This setting is only effective if `lfs` is `true`.
	LfsEndpoint *string `json:"lfsEndpoint,omitempty" tf:"lfs_endpoint,omitempty"`

	// (String) License to use. Changing this forces a new resource to be created.
	// License to use. Changing this forces a new resource to be created.
	License *string `json:"license,omitempty" tf:"license,omitempty"`

	// (Boolean) Whether to migrate milestones. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate milestones. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Milestones *bool `json:"milestones,omitempty" tf:"milestones,omitempty"`

	// (Boolean) Is the repository a mirror? Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Is the repository a mirror? Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Mirror *bool `json:"mirror,omitempty" tf:"mirror,omitempty"`

	// (String) Mirror interval of the repository. Note: This setting is only effective if mirror is true.
	// Mirror interval of the repository. **Note**: This setting is only effective if `mirror` is `true`.
	MirrorInterval *string `json:"mirrorInterval,omitempty" tf:"mirror_interval,omitempty"`

	// (String) Name of the repository.
	// Name of the repository.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Owner of the repository (user or organization). Changing this forces a new resource to be created.
	// Owner of the repository (user or organization). Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.Organization
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Reference to a Organization in forgejo to populate owner.
	// +kubebuilder:validation:Optional
	OwnerRef *v2.Reference `json:"ownerRef,omitempty" tf:"-"`

	// Selector for a Organization in forgejo to populate owner.
	// +kubebuilder:validation:Optional
	OwnerSelector *v2.Selector `json:"ownerSelector,omitempty" tf:"-"`

	// (Boolean) Is the repository private?
	// Is the repository private?
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Readme of the repository to create. Changing this forces a new resource to be created.
	// Readme of the repository to create. Changing this forces a new resource to be created.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) Service to migrate from. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Service to migrate from. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// (Boolean) Is the repository a template?
	// Is the repository a template?
	Template *bool `json:"template,omitempty" tf:"template,omitempty"`

	// (String) TrustModel of the repository. Changing this forces a new resource to be created.
	// TrustModel of the repository. Changing this forces a new resource to be created.
	TrustModel *string `json:"trustModel,omitempty" tf:"trust_model,omitempty"`

	// (String) Website of the repository.
	// Website of the repository.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`

	// (String) Branch used for the repository wiki. Note: This setting is only effective if has_wiki is true.
	// Branch used for the repository wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
	WikiBranch *string `json:"wikiBranch,omitempty" tf:"wiki_branch,omitempty"`
}

type RepositoryObservation struct {

	// forward-only merge pull requests? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to fast-forward-only merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowFastForwardOnlyMerge *bool `json:"allowFastForwardOnlyMerge,omitempty" tf:"allow_fast_forward_only_merge,omitempty"`

	// (Boolean) Allowed to manually merge pull requests? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to manually merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowManualMerge *bool `json:"allowManualMerge,omitempty" tf:"allow_manual_merge,omitempty"`

	// (Boolean) Allowed to create merge commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowMergeCommits *bool `json:"allowMergeCommits,omitempty" tf:"allow_merge_commits,omitempty"`

	// forward? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to rebase then fast-forward? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowRebase *bool `json:"allowRebase,omitempty" tf:"allow_rebase,omitempty"`

	// (Boolean) Allowed to rebase then create merge commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to rebase then create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowRebaseExplicit *bool `json:"allowRebaseExplicit,omitempty" tf:"allow_rebase_explicit,omitempty"`

	// (Boolean) Allowed to update pull request branch by rebase? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to update pull request branch by rebase? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowRebaseUpdate *bool `json:"allowRebaseUpdate,omitempty" tf:"allow_rebase_update,omitempty"`

	// (Boolean) Allowed to create squash commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to create squash commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AllowSquashMerge *bool `json:"allowSquashMerge,omitempty" tf:"allow_squash_merge,omitempty"`

	// (Boolean) Archive the repo instead of delete?
	// Archive the repo instead of delete?
	ArchiveOnDestroy *bool `json:"archiveOnDestroy,omitempty" tf:"archive_on_destroy,omitempty"`

	// (Boolean) Is the repository archived?
	// Is the repository archived?
	Archived *bool `json:"archived,omitempty" tf:"archived,omitempty"`

	// intialized? Changing this forces a new resource to be created.
	// Whether the repository should be auto-intialized? Changing this forces a new resource to be created.
	AutoInit *bool `json:"autoInit,omitempty" tf:"auto_init,omitempty"`

	// detect manual pull request merges? Note: This setting is only effective if has_pull_requests is true.
	// Auto-detect manual pull request merges? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	AutodetectManualMerge *bool `json:"autodetectManualMerge,omitempty" tf:"autodetect_manual_merge,omitempty"`

	// (String) Avatar URL of the repository.
	// Avatar URL of the repository.
	AvatarURL *string `json:"avatarUrl,omitempty" tf:"avatar_url,omitempty"`

	// (String) Migrate / clone from URL. Changing this forces a new resource to be created.
	// Migrate / clone from URL. Changing this forces a new resource to be created.
	CloneAddr *string `json:"cloneAddr,omitempty" tf:"clone_addr,omitempty"`

	// (String) Clone URL of the repository.
	// Clone URL of the repository.
	CloneURL *string `json:"cloneUrl,omitempty" tf:"clone_url,omitempty"`

	// (String) Time at which the repository was created.
	// Time at which the repository was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Allow maintainer edits on pull requests by default? Note: This setting is only effective if has_pull_requests is true.
	// Allow maintainer edits on pull requests by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultAllowMaintainerEdit *bool `json:"defaultAllowMaintainerEdit,omitempty" tf:"default_allow_maintainer_edit,omitempty"`

	// (String) Default branch of the repository.
	// Default branch of the repository.
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// (Boolean) Delete pull request branch after merge by default? Note: This setting is only effective if has_pull_requests is true.
	// Delete pull request branch after merge by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultDeleteBranchAfterMerge *bool `json:"defaultDeleteBranchAfterMerge,omitempty" tf:"default_delete_branch_after_merge,omitempty"`

	// (String) Default merge style of the repository. Note: This setting is only effective if has_pull_requests is true.
	// Default merge style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultMergeStyle *string `json:"defaultMergeStyle,omitempty" tf:"default_merge_style,omitempty"`

	// (String) Default pull request update style of the repository. Note: This setting is only effective if has_pull_requests is true.
	// Default pull request update style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
	DefaultUpdateStyle *string `json:"defaultUpdateStyle,omitempty" tf:"default_update_style,omitempty"`

	// (String) Description of the repository.
	// Description of the repository.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Is the repository empty?
	// Is the repository empty?
	Empty *bool `json:"empty,omitempty" tf:"empty,omitempty"`

	// tracking references when mirroring? Note: This setting is only effective if mirror is true.
	// Remove obsolete remote-tracking references when mirroring? **Note**: This setting is only effective if `mirror` is `true`.
	EnablePrune *bool `json:"enablePrune,omitempty" tf:"enable_prune,omitempty"`

	// (Attributes) Settings for external issue tracker. Note: This setting is only effective if has_issues is true. (see below for nested schema)
	ExternalTracker *ExternalTrackerObservation `json:"externalTracker,omitempty" tf:"external_tracker,omitempty"`

	// (Attributes) Settings for external wiki. Note: This setting is only effective if has_wiki is true. (see below for nested schema)
	ExternalWiki *ExternalWikiObservation `json:"externalWiki,omitempty" tf:"external_wiki,omitempty"`

	// (Boolean) Is the repository a fork?
	// Is the repository a fork?
	Fork *bool `json:"fork,omitempty" tf:"fork,omitempty"`

	// (Number) Number of forks of the repository.
	// Number of forks of the repository.
	ForksCount *float64 `json:"forksCount,omitempty" tf:"forks_count,omitempty"`

	// (String) Full name of the repository.
	// Full name of the repository.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Gitignores to use. Changing this forces a new resource to be created.
	// Gitignores to use. Changing this forces a new resource to be created.
	Gitignores *string `json:"gitignores,omitempty" tf:"gitignores,omitempty"`

	// (Boolean) Is the repository wiki globally editable? Note: This setting is only effective if has_wiki is true.
	// Is the repository wiki globally editable? **Note**: This setting is only effective if `has_wiki` is `true`.
	GloballyEditableWiki *bool `json:"globallyEditableWiki,omitempty" tf:"globally_editable_wiki,omitempty"`

	// (String) HTML URL of the repository.
	// HTML URL of the repository.
	HTMLURL *string `json:"htmlUrl,omitempty" tf:"html_url,omitempty"`

	// (Boolean) Are integrated CI/CD pipelines enabled?
	// Are integrated CI/CD pipelines enabled?
	HasActions *bool `json:"hasActions,omitempty" tf:"has_actions,omitempty"`

	// (Boolean) Is the repository issue tracker enabled?
	// Is the repository issue tracker enabled?
	HasIssues *bool `json:"hasIssues,omitempty" tf:"has_issues,omitempty"`

	// (Boolean) Is the repository package registry enabled?
	// Is the repository package registry enabled?
	HasPackages *bool `json:"hasPackages,omitempty" tf:"has_packages,omitempty"`

	// (Boolean) Are repository projects enabled?
	// Are repository projects enabled?
	HasProjects *bool `json:"hasProjects,omitempty" tf:"has_projects,omitempty"`

	// (Boolean) Are repository pull requests enabled?
	// Are repository pull requests enabled?
	HasPullRequests *bool `json:"hasPullRequests,omitempty" tf:"has_pull_requests,omitempty"`

	// (Boolean) Are repository releases enabled?
	// Are repository releases enabled?
	HasReleases *bool `json:"hasReleases,omitempty" tf:"has_releases,omitempty"`

	// (Boolean) Is the repository wiki enabled?
	// Is the repository wiki enabled?
	HasWiki *bool `json:"hasWiki,omitempty" tf:"has_wiki,omitempty"`

	// (Number) Numeric identifier of the repository.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Are whitespace conflicts ignored? Note: This setting is only effective if has_pull_requests is true.
	// Are whitespace conflicts ignored? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	IgnoreWhitespaceConflicts *bool `json:"ignoreWhitespaceConflicts,omitempty" tf:"ignore_whitespace_conflicts,omitempty"`

	// (Boolean) Is the repository internal?
	// Is the repository internal?
	Internal *bool `json:"internal,omitempty" tf:"internal,omitempty"`

	// in issue tracker. Note: This setting is only effective if has_issues is true. (see below for nested schema)
	InternalTracker *InternalTrackerObservation `json:"internalTracker,omitempty" tf:"internal_tracker,omitempty"`

	// (String) Issue Label set to use. Changing this forces a new resource to be created.
	// Issue Label set to use. Changing this forces a new resource to be created.
	IssueLabels *string `json:"issueLabels,omitempty" tf:"issue_labels,omitempty"`

	// (Boolean) Whether to migrate labels. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate labels. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Labels *bool `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Boolean) Whether to migrate LFS files. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate LFS files. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Lfs *bool `json:"lfs,omitempty" tf:"lfs,omitempty"`

	// (String) LFS endpoint to use. Changing this forces a new resource to be created. Note: This setting is only effective if lfs is true.
	// LFS endpoint to use. Changing this forces a new resource to be created. **Note**: This setting is only effective if `lfs` is `true`.
	LfsEndpoint *string `json:"lfsEndpoint,omitempty" tf:"lfs_endpoint,omitempty"`

	// (String) License to use. Changing this forces a new resource to be created.
	// License to use. Changing this forces a new resource to be created.
	License *string `json:"license,omitempty" tf:"license,omitempty"`

	// (Boolean) Whether to migrate milestones. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate milestones. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Milestones *bool `json:"milestones,omitempty" tf:"milestones,omitempty"`

	// (Boolean) Is the repository a mirror? Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Is the repository a mirror? Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Mirror *bool `json:"mirror,omitempty" tf:"mirror,omitempty"`

	// (String) Mirror interval of the repository. Note: This setting is only effective if mirror is true.
	// Mirror interval of the repository. **Note**: This setting is only effective if `mirror` is `true`.
	MirrorInterval *string `json:"mirrorInterval,omitempty" tf:"mirror_interval,omitempty"`

	// (String) Time at which the repository mirror was updated.
	// Time at which the repository mirror was updated.
	MirrorUpdated *string `json:"mirrorUpdated,omitempty" tf:"mirror_updated,omitempty"`

	// (String) Name of the repository.
	// Name of the repository.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Number of open issues of the repository.
	// Number of open issues of the repository.
	OpenIssuesCount *float64 `json:"openIssuesCount,omitempty" tf:"open_issues_count,omitempty"`

	// (Number) Number of open pull requests of the repository.
	// Number of open pull requests of the repository.
	OpenPrCounter *float64 `json:"openPrCounter,omitempty" tf:"open_pr_counter,omitempty"`

	// (String) Owner of the repository (user or organization). Changing this forces a new resource to be created.
	// Owner of the repository (user or organization). Changing this forces a new resource to be created.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (Number) Numeric identifier of the parent repository.
	// Numeric identifier of the parent repository.
	ParentID *float64 `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Attributes) Permissions of the repository. (see below for nested schema)
	Permissions *PermissionsObservation `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (Boolean) Is the repository private?
	// Is the repository private?
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Readme of the repository to create. Changing this forces a new resource to be created.
	// Readme of the repository to create. Changing this forces a new resource to be created.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (Number) Number of releases of the repository.
	// Number of releases of the repository.
	ReleaseCounter *float64 `json:"releaseCounter,omitempty" tf:"release_counter,omitempty"`

	// (String) SSH URL of the repository.
	// SSH URL of the repository.
	SSHURL *string `json:"sshUrl,omitempty" tf:"ssh_url,omitempty"`

	// (String) Service to migrate from. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Service to migrate from. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// (Number) Size of the repository in KiB.
	// Size of the repository in KiB.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (Number) Number of stars of the repository.
	// Number of stars of the repository.
	StarsCount *float64 `json:"starsCount,omitempty" tf:"stars_count,omitempty"`

	// (Boolean) Is the repository a template?
	// Is the repository a template?
	Template *bool `json:"template,omitempty" tf:"template,omitempty"`

	// (String) TrustModel of the repository. Changing this forces a new resource to be created.
	// TrustModel of the repository. Changing this forces a new resource to be created.
	TrustModel *string `json:"trustModel,omitempty" tf:"trust_model,omitempty"`

	// (String) Time at which the repository was updated.
	// Time at which the repository was updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (Number) Number of watchers of the repository.
	// Number of watchers of the repository.
	WatchersCount *float64 `json:"watchersCount,omitempty" tf:"watchers_count,omitempty"`

	// (String) Website of the repository.
	// Website of the repository.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`

	// (String) Branch used for the repository wiki. Note: This setting is only effective if has_wiki is true.
	// Branch used for the repository wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
	WikiBranch *string `json:"wikiBranch,omitempty" tf:"wiki_branch,omitempty"`
}

type RepositoryParameters struct {

	// forward-only merge pull requests? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to fast-forward-only merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AllowFastForwardOnlyMerge *bool `json:"allowFastForwardOnlyMerge,omitempty" tf:"allow_fast_forward_only_merge,omitempty"`

	// (Boolean) Allowed to manually merge pull requests? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to manually merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AllowManualMerge *bool `json:"allowManualMerge,omitempty" tf:"allow_manual_merge,omitempty"`

	// (Boolean) Allowed to create merge commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AllowMergeCommits *bool `json:"allowMergeCommits,omitempty" tf:"allow_merge_commits,omitempty"`

	// forward? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to rebase then fast-forward? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AllowRebase *bool `json:"allowRebase,omitempty" tf:"allow_rebase,omitempty"`

	// (Boolean) Allowed to rebase then create merge commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to rebase then create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AllowRebaseExplicit *bool `json:"allowRebaseExplicit,omitempty" tf:"allow_rebase_explicit,omitempty"`

	// (Boolean) Allowed to update pull request branch by rebase? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to update pull request branch by rebase? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AllowRebaseUpdate *bool `json:"allowRebaseUpdate,omitempty" tf:"allow_rebase_update,omitempty"`

	// (Boolean) Allowed to create squash commit? Note: This setting is only effective if has_pull_requests is true.
	// Allowed to create squash commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AllowSquashMerge *bool `json:"allowSquashMerge,omitempty" tf:"allow_squash_merge,omitempty"`

	// (Boolean) Archive the repo instead of delete?
	// Archive the repo instead of delete?
	// +kubebuilder:validation:Optional
	ArchiveOnDestroy *bool `json:"archiveOnDestroy,omitempty" tf:"archive_on_destroy,omitempty"`

	// (Boolean) Is the repository archived?
	// Is the repository archived?
	// +kubebuilder:validation:Optional
	Archived *bool `json:"archived,omitempty" tf:"archived,omitempty"`

	// (String, Sensitive) API token for authenticating with migrate / clone URL. Note: This setting is only effective if clone_addr is set.
	// API token for authenticating with migrate / clone URL. **Note**: This setting is only effective if `clone_addr` is set.
	// +kubebuilder:validation:Optional
	AuthTokenSecretRef *v2.SecretKeySelector `json:"authTokenSecretRef,omitempty" tf:"-"`

	// intialized? Changing this forces a new resource to be created.
	// Whether the repository should be auto-intialized? Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	AutoInit *bool `json:"autoInit,omitempty" tf:"auto_init,omitempty"`

	// detect manual pull request merges? Note: This setting is only effective if has_pull_requests is true.
	// Auto-detect manual pull request merges? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	AutodetectManualMerge *bool `json:"autodetectManualMerge,omitempty" tf:"autodetect_manual_merge,omitempty"`

	// (String) Migrate / clone from URL. Changing this forces a new resource to be created.
	// Migrate / clone from URL. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	CloneAddr *string `json:"cloneAddr,omitempty" tf:"clone_addr,omitempty"`

	// (Boolean) Allow maintainer edits on pull requests by default? Note: This setting is only effective if has_pull_requests is true.
	// Allow maintainer edits on pull requests by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	DefaultAllowMaintainerEdit *bool `json:"defaultAllowMaintainerEdit,omitempty" tf:"default_allow_maintainer_edit,omitempty"`

	// (String) Default branch of the repository.
	// Default branch of the repository.
	// +kubebuilder:validation:Optional
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// (Boolean) Delete pull request branch after merge by default? Note: This setting is only effective if has_pull_requests is true.
	// Delete pull request branch after merge by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	DefaultDeleteBranchAfterMerge *bool `json:"defaultDeleteBranchAfterMerge,omitempty" tf:"default_delete_branch_after_merge,omitempty"`

	// (String) Default merge style of the repository. Note: This setting is only effective if has_pull_requests is true.
	// Default merge style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	DefaultMergeStyle *string `json:"defaultMergeStyle,omitempty" tf:"default_merge_style,omitempty"`

	// (String) Default pull request update style of the repository. Note: This setting is only effective if has_pull_requests is true.
	// Default pull request update style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	DefaultUpdateStyle *string `json:"defaultUpdateStyle,omitempty" tf:"default_update_style,omitempty"`

	// (String) Description of the repository.
	// Description of the repository.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// tracking references when mirroring? Note: This setting is only effective if mirror is true.
	// Remove obsolete remote-tracking references when mirroring? **Note**: This setting is only effective if `mirror` is `true`.
	// +kubebuilder:validation:Optional
	EnablePrune *bool `json:"enablePrune,omitempty" tf:"enable_prune,omitempty"`

	// (Attributes) Settings for external issue tracker. Note: This setting is only effective if has_issues is true. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ExternalTracker *ExternalTrackerParameters `json:"externalTracker,omitempty" tf:"external_tracker,omitempty"`

	// (Attributes) Settings for external wiki. Note: This setting is only effective if has_wiki is true. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ExternalWiki *ExternalWikiParameters `json:"externalWiki,omitempty" tf:"external_wiki,omitempty"`

	// (String) Gitignores to use. Changing this forces a new resource to be created.
	// Gitignores to use. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Gitignores *string `json:"gitignores,omitempty" tf:"gitignores,omitempty"`

	// (Boolean) Is the repository wiki globally editable? Note: This setting is only effective if has_wiki is true.
	// Is the repository wiki globally editable? **Note**: This setting is only effective if `has_wiki` is `true`.
	// +kubebuilder:validation:Optional
	GloballyEditableWiki *bool `json:"globallyEditableWiki,omitempty" tf:"globally_editable_wiki,omitempty"`

	// (Boolean) Are integrated CI/CD pipelines enabled?
	// Are integrated CI/CD pipelines enabled?
	// +kubebuilder:validation:Optional
	HasActions *bool `json:"hasActions,omitempty" tf:"has_actions,omitempty"`

	// (Boolean) Is the repository issue tracker enabled?
	// Is the repository issue tracker enabled?
	// +kubebuilder:validation:Optional
	HasIssues *bool `json:"hasIssues,omitempty" tf:"has_issues,omitempty"`

	// (Boolean) Is the repository package registry enabled?
	// Is the repository package registry enabled?
	// +kubebuilder:validation:Optional
	HasPackages *bool `json:"hasPackages,omitempty" tf:"has_packages,omitempty"`

	// (Boolean) Are repository projects enabled?
	// Are repository projects enabled?
	// +kubebuilder:validation:Optional
	HasProjects *bool `json:"hasProjects,omitempty" tf:"has_projects,omitempty"`

	// (Boolean) Are repository pull requests enabled?
	// Are repository pull requests enabled?
	// +kubebuilder:validation:Optional
	HasPullRequests *bool `json:"hasPullRequests,omitempty" tf:"has_pull_requests,omitempty"`

	// (Boolean) Are repository releases enabled?
	// Are repository releases enabled?
	// +kubebuilder:validation:Optional
	HasReleases *bool `json:"hasReleases,omitempty" tf:"has_releases,omitempty"`

	// (Boolean) Is the repository wiki enabled?
	// Is the repository wiki enabled?
	// +kubebuilder:validation:Optional
	HasWiki *bool `json:"hasWiki,omitempty" tf:"has_wiki,omitempty"`

	// (Boolean) Are whitespace conflicts ignored? Note: This setting is only effective if has_pull_requests is true.
	// Are whitespace conflicts ignored? **Note**: This setting is only effective if `has_pull_requests` is `true`.
	// +kubebuilder:validation:Optional
	IgnoreWhitespaceConflicts *bool `json:"ignoreWhitespaceConflicts,omitempty" tf:"ignore_whitespace_conflicts,omitempty"`

	// in issue tracker. Note: This setting is only effective if has_issues is true. (see below for nested schema)
	// +kubebuilder:validation:Optional
	InternalTracker *InternalTrackerParameters `json:"internalTracker,omitempty" tf:"internal_tracker,omitempty"`

	// (String) Issue Label set to use. Changing this forces a new resource to be created.
	// Issue Label set to use. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	IssueLabels *string `json:"issueLabels,omitempty" tf:"issue_labels,omitempty"`

	// (Boolean) Whether to migrate labels. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate labels. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	// +kubebuilder:validation:Optional
	Labels *bool `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Boolean) Whether to migrate LFS files. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate LFS files. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	// +kubebuilder:validation:Optional
	Lfs *bool `json:"lfs,omitempty" tf:"lfs,omitempty"`

	// (String) LFS endpoint to use. Changing this forces a new resource to be created. Note: This setting is only effective if lfs is true.
	// LFS endpoint to use. Changing this forces a new resource to be created. **Note**: This setting is only effective if `lfs` is `true`.
	// +kubebuilder:validation:Optional
	LfsEndpoint *string `json:"lfsEndpoint,omitempty" tf:"lfs_endpoint,omitempty"`

	// (String) License to use. Changing this forces a new resource to be created.
	// License to use. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	License *string `json:"license,omitempty" tf:"license,omitempty"`

	// (Boolean) Whether to migrate milestones. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Whether to migrate milestones. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	// +kubebuilder:validation:Optional
	Milestones *bool `json:"milestones,omitempty" tf:"milestones,omitempty"`

	// (Boolean) Is the repository a mirror? Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Is the repository a mirror? Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	// +kubebuilder:validation:Optional
	Mirror *bool `json:"mirror,omitempty" tf:"mirror,omitempty"`

	// (String) Mirror interval of the repository. Note: This setting is only effective if mirror is true.
	// Mirror interval of the repository. **Note**: This setting is only effective if `mirror` is `true`.
	// +kubebuilder:validation:Optional
	MirrorInterval *string `json:"mirrorInterval,omitempty" tf:"mirror_interval,omitempty"`

	// (String) Name of the repository.
	// Name of the repository.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Owner of the repository (user or organization). Changing this forces a new resource to be created.
	// Owner of the repository (user or organization). Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Reference to a Organization in forgejo to populate owner.
	// +kubebuilder:validation:Optional
	OwnerRef *v2.Reference `json:"ownerRef,omitempty" tf:"-"`

	// Selector for a Organization in forgejo to populate owner.
	// +kubebuilder:validation:Optional
	OwnerSelector *v2.Selector `json:"ownerSelector,omitempty" tf:"-"`

	// (Boolean) Is the repository private?
	// Is the repository private?
	// +kubebuilder:validation:Optional
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Readme of the repository to create. Changing this forces a new resource to be created.
	// Readme of the repository to create. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) Service to migrate from. Changing this forces a new resource to be created. Note: This setting is only effective if clone_addr is set.
	// Service to migrate from. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// (Boolean) Is the repository a template?
	// Is the repository a template?
	// +kubebuilder:validation:Optional
	Template *bool `json:"template,omitempty" tf:"template,omitempty"`

	// (String) TrustModel of the repository. Changing this forces a new resource to be created.
	// TrustModel of the repository. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	TrustModel *string `json:"trustModel,omitempty" tf:"trust_model,omitempty"`

	// (String) Website of the repository.
	// Website of the repository.
	// +kubebuilder:validation:Optional
	Website *string `json:"website,omitempty" tf:"website,omitempty"`

	// (String) Branch used for the repository wiki. Note: This setting is only effective if has_wiki is true.
	// Branch used for the repository wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
	// +kubebuilder:validation:Optional
	WikiBranch *string `json:"wikiBranch,omitempty" tf:"wiki_branch,omitempty"`
}

// RepositorySpec defines the desired state of Repository
type RepositorySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryInitParameters `json:"initProvider,omitempty"`
}

// RepositoryStatus defines the observed state of Repository.
type RepositoryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Repository is the Schema for the Repositorys API. Forgejo repository resource. Note: Managing user repositories requires administrative privileges!
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type Repository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RepositorySpec   `json:"spec"`
	Status RepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryList contains a list of Repositorys
type RepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Repository `json:"items"`
}

// Repository type metadata.
var (
	Repository_Kind             = "Repository"
	Repository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Repository_Kind}.String()
	Repository_KindAPIVersion   = Repository_Kind + "." + CRDGroupVersion.String()
	Repository_GroupVersionKind = CRDGroupVersion.WithKind(Repository_Kind)
)

func init() {
	SchemeBuilder.Register(&Repository{}, &RepositoryList{})
}
