// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SshKeyInitParameters struct {

	// (String) Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) Title of the SSH key. Changing this forces a new resource to be created.
	// Title of the SSH key. Changing this forces a new resource to be created.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type SshKeyObservation struct {

	// (String) Time at which the SSH key was created.
	// Time at which the SSH key was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Fingerprint of the SSH key.
	// Fingerprint of the SSH key.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Number) Numeric identifier of the SSH key.
	// Numeric identifier of the SSH key.
	KeyID *float64 `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) Type of the SSH key.
	// Type of the SSH key.
	KeyType *string `json:"keyType,omitempty" tf:"key_type,omitempty"`

	// (Boolean) Does the key have only read access?
	// Does the key have only read access?
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (String) Title of the SSH key. Changing this forces a new resource to be created.
	// Title of the SSH key. Changing this forces a new resource to be created.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (String) URL of the SSH key.
	// URL of the SSH key.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type SshKeyParameters struct {

	// (String) Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) Title of the SSH key. Changing this forces a new resource to be created.
	// Title of the SSH key. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

// SshKeySpec defines the desired state of SshKey
type SshKeySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SshKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SshKeyInitParameters `json:"initProvider,omitempty"`
}

// SshKeyStatus defines the observed state of SshKey.
type SshKeyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SshKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SshKey is the Schema for the SshKeys API. Forgejo user SSH key resource. Note: Managing user SSH keys requires administrative privileges!
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type SshKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.user) || (has(self.initProvider) && has(self.initProvider.user))",message="spec.forProvider.user is a required parameter"
	Spec   SshKeySpec   `json:"spec"`
	Status SshKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SshKeyList contains a list of SshKeys
type SshKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SshKey `json:"items"`
}

// Repository type metadata.
var (
	SshKey_Kind             = "SshKey"
	SshKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SshKey_Kind}.String()
	SshKey_KindAPIVersion   = SshKey_Kind + "." + CRDGroupVersion.String()
	SshKey_GroupVersionKind = CRDGroupVersion.WithKind(SshKey_Kind)
)

func init() {
	SchemeBuilder.Register(&SshKey{}, &SshKeyList{})
}
