// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TeamInitParameters struct {

	// (Boolean) Can create repositories?
	// Can create repositories?
	CanCreateOrgRepo *bool `json:"canCreateOrgRepo,omitempty" tf:"can_create_org_repo,omitempty"`

	// (String) Description of the team.
	// Description of the team.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Has access to all repositories?
	// Has access to all repositories?
	IncludesAllRepositories *bool `json:"includesAllRepositories,omitempty" tf:"includes_all_repositories,omitempty"`

	// (String) Name of the team.
	// Name of the team.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.Organization
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in forgejo to populate organization.
	// +kubebuilder:validation:Optional
	OrganizationRef *v2.Reference `json:"organizationRef,omitempty" tf:"-"`

	// Selector for a Organization in forgejo to populate organization.
	// +kubebuilder:validation:Optional
	OrganizationSelector *v2.Selector `json:"organizationSelector,omitempty" tf:"-"`

	// (String) Permissions within the owning organization. Note: If you set admin or owner here, make sure to set the correct units_map.
	// Permissions within the owning organization. **Note**: If you set `admin` or `owner` here, make sure to set the correct `units_map`.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (Map of String) Map of access units. Note: If the permission is admin or owner all units must be set to admin as well.
	// Map of access units. **Note**: If the `permission` is `admin` or `owner` all units must be set to `admin` as well.
	// +mapType=granular
	UnitsMap map[string]*string `json:"unitsMap,omitempty" tf:"units_map,omitempty"`
}

type TeamObservation struct {

	// (Boolean) Can create repositories?
	// Can create repositories?
	CanCreateOrgRepo *bool `json:"canCreateOrgRepo,omitempty" tf:"can_create_org_repo,omitempty"`

	// (String) Description of the team.
	// Description of the team.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) Numeric identifier of the team.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Has access to all repositories?
	// Has access to all repositories?
	IncludesAllRepositories *bool `json:"includesAllRepositories,omitempty" tf:"includes_all_repositories,omitempty"`

	// (String) Name of the team.
	// Name of the team.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) Permissions within the owning organization. Note: If you set admin or owner here, make sure to set the correct units_map.
	// Permissions within the owning organization. **Note**: If you set `admin` or `owner` here, make sure to set the correct `units_map`.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (Map of String) Map of access units. Note: If the permission is admin or owner all units must be set to admin as well.
	// Map of access units. **Note**: If the `permission` is `admin` or `owner` all units must be set to `admin` as well.
	// +mapType=granular
	UnitsMap map[string]*string `json:"unitsMap,omitempty" tf:"units_map,omitempty"`
}

type TeamParameters struct {

	// (Boolean) Can create repositories?
	// Can create repositories?
	// +kubebuilder:validation:Optional
	CanCreateOrgRepo *bool `json:"canCreateOrgRepo,omitempty" tf:"can_create_org_repo,omitempty"`

	// (String) Description of the team.
	// Description of the team.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Has access to all repositories?
	// Has access to all repositories?
	// +kubebuilder:validation:Optional
	IncludesAllRepositories *bool `json:"includesAllRepositories,omitempty" tf:"includes_all_repositories,omitempty"`

	// (String) Name of the team.
	// Name of the team.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	// +kubebuilder:validation:Optional
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Reference to a Organization in forgejo to populate organization.
	// +kubebuilder:validation:Optional
	OrganizationRef *v2.Reference `json:"organizationRef,omitempty" tf:"-"`

	// Selector for a Organization in forgejo to populate organization.
	// +kubebuilder:validation:Optional
	OrganizationSelector *v2.Selector `json:"organizationSelector,omitempty" tf:"-"`

	// (String) Permissions within the owning organization. Note: If you set admin or owner here, make sure to set the correct units_map.
	// Permissions within the owning organization. **Note**: If you set `admin` or `owner` here, make sure to set the correct `units_map`.
	// +kubebuilder:validation:Optional
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (Map of String) Map of access units. Note: If the permission is admin or owner all units must be set to admin as well.
	// Map of access units. **Note**: If the `permission` is `admin` or `owner` all units must be set to `admin` as well.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	UnitsMap map[string]*string `json:"unitsMap,omitempty" tf:"units_map,omitempty"`
}

// TeamSpec defines the desired state of Team
type TeamSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TeamParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamInitParameters `json:"initProvider,omitempty"`
}

// TeamStatus defines the observed state of Team.
type TeamStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TeamObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Team is the Schema for the Teams API. Forgejo team resource. Note: The authenticated user must be a member of the managed organization(s) or have administrative privileges!
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type Team struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.unitsMap) || (has(self.initProvider) && has(self.initProvider.unitsMap))",message="spec.forProvider.unitsMap is a required parameter"
	Spec   TeamSpec   `json:"spec"`
	Status TeamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamList contains a list of Teams
type TeamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Team `json:"items"`
}

// Repository type metadata.
var (
	Team_Kind             = "Team"
	Team_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Team_Kind}.String()
	Team_KindAPIVersion   = Team_Kind + "." + CRDGroupVersion.String()
	Team_GroupVersionKind = CRDGroupVersion.WithKind(Team_Kind)
)

func init() {
	SchemeBuilder.Register(&Team{}, &TeamList{})
}
