// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TeamMemberInitParameters struct {

	// (Number) Numeric identifier of the team. Changing this forces a new resource to be created.
	// Numeric identifier of the team. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.Team
	TeamID *float64 `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in forgejo to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v2.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in forgejo to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v2.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// (String) Username of the team member. Changing this forces a new resource to be created.
	// Username of the team member. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.User
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.Reference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.Selector `json:"userSelector,omitempty" tf:"-"`
}

type TeamMemberObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Numeric identifier of the team. Changing this forces a new resource to be created.
	// Numeric identifier of the team. Changing this forces a new resource to be created.
	TeamID *float64 `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// (String) Username of the team member. Changing this forces a new resource to be created.
	// Username of the team member. Changing this forces a new resource to be created.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type TeamMemberParameters struct {

	// (Number) Numeric identifier of the team. Changing this forces a new resource to be created.
	// Numeric identifier of the team. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.Team
	// +kubebuilder:validation:Optional
	TeamID *float64 `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in forgejo to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v2.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in forgejo to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v2.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// (String) Username of the team member. Changing this forces a new resource to be created.
	// Username of the team member. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/cluster/forgejo/v1alpha1.User
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.Reference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.Selector `json:"userSelector,omitempty" tf:"-"`
}

// TeamMemberSpec defines the desired state of TeamMember
type TeamMemberSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TeamMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamMemberInitParameters `json:"initProvider,omitempty"`
}

// TeamMemberStatus defines the observed state of TeamMember.
type TeamMemberStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TeamMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamMember is the Schema for the TeamMembers API. Forgejo team member resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type TeamMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TeamMemberSpec   `json:"spec"`
	Status            TeamMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamMemberList contains a list of TeamMembers
type TeamMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamMember `json:"items"`
}

// Repository type metadata.
var (
	TeamMember_Kind             = "TeamMember"
	TeamMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamMember_Kind}.String()
	TeamMember_KindAPIVersion   = TeamMember_Kind + "." + CRDGroupVersion.String()
	TeamMember_GroupVersionKind = CRDGroupVersion.WithKind(TeamMember_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamMember{}, &TeamMemberList{})
}
