// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type UserInitParameters struct {

	// (Boolean) Is the user active?
	// Is the user active?
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Boolean) Is the user an administrator?
	// Is the user an administrator?
	Admin *bool `json:"admin,omitempty" tf:"admin,omitempty"`

	// (Boolean) Allow user to create organizations?
	// Allow user to create organizations?
	AllowCreateOrganization *bool `json:"allowCreateOrganization,omitempty" tf:"allow_create_organization,omitempty"`

	// (Boolean) Allow user to create Git hooks?
	// Allow user to create Git hooks?
	AllowGitHook *bool `json:"allowGitHook,omitempty" tf:"allow_git_hook,omitempty"`

	// (Boolean) Allow user to import local repositories?
	// Allow user to import local repositories?
	AllowImportLocal *bool `json:"allowImportLocal,omitempty" tf:"allow_import_local,omitempty"`

	// (Boolean) Deactivate the user instead of delete?
	// Deactivate the user instead of delete?
	DeactivateOnDestroy *bool `json:"deactivateOnDestroy,omitempty" tf:"deactivate_on_destroy,omitempty"`

	// (String) Description of the user.
	// Description of the user.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Email address of the user.
	// Email address of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Full name of the user.
	// Full name of the user.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Location of the user.
	// Location of the user.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Login name of the user.
	// Login name of the user.
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// 1 means no limit.
	// Maximum number of repositories user can create. A value of -1 means no limit.
	MaxRepoCreation *float64 `json:"maxRepoCreation,omitempty" tf:"max_repo_creation,omitempty"`

	// (Boolean) Require user to change password?
	// Require user to change password?
	MustChangePassword *bool `json:"mustChangePassword,omitempty" tf:"must_change_password,omitempty"`

	// (String, Sensitive) Password of the user.
	// Password of the user.
	PasswordSecretRef v2.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Boolean) Are user logins prohibited?
	// Are user logins prohibited?
	ProhibitLogin *bool `json:"prohibitLogin,omitempty" tf:"prohibit_login,omitempty"`

	// (Boolean) Is the user restricted?
	// Is the user restricted?
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// (Boolean) Send notification to administrators? Changing this forces a new resource to be created.
	// Send notification to administrators? Changing this forces a new resource to be created.
	SendNotify *bool `json:"sendNotify,omitempty" tf:"send_notify,omitempty"`

	// (Number) Numeric identifier of the user's authentication source.
	// Numeric identifier of the user's authentication source.
	SourceID *float64 `json:"sourceId,omitempty" tf:"source_id,omitempty"`

	// (String) Visibility of the user. Possible values are 'public' (default), 'limited', or 'private'.
	// Visibility of the user. Possible values are 'public' (default), 'limited', or 'private'.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) Website of the user.
	// Website of the user.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type UserObservation struct {

	// (Boolean) Is the user active?
	// Is the user active?
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Boolean) Is the user an administrator?
	// Is the user an administrator?
	Admin *bool `json:"admin,omitempty" tf:"admin,omitempty"`

	// (Boolean) Allow user to create organizations?
	// Allow user to create organizations?
	AllowCreateOrganization *bool `json:"allowCreateOrganization,omitempty" tf:"allow_create_organization,omitempty"`

	// (Boolean) Allow user to create Git hooks?
	// Allow user to create Git hooks?
	AllowGitHook *bool `json:"allowGitHook,omitempty" tf:"allow_git_hook,omitempty"`

	// (Boolean) Allow user to import local repositories?
	// Allow user to import local repositories?
	AllowImportLocal *bool `json:"allowImportLocal,omitempty" tf:"allow_import_local,omitempty"`

	// (String) Avatar URL of the user.
	// Avatar URL of the user.
	AvatarURL *string `json:"avatarUrl,omitempty" tf:"avatar_url,omitempty"`

	// (String) Time at which the user was created.
	// Time at which the user was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Deactivate the user instead of delete?
	// Deactivate the user instead of delete?
	DeactivateOnDestroy *bool `json:"deactivateOnDestroy,omitempty" tf:"deactivate_on_destroy,omitempty"`

	// (String) Description of the user.
	// Description of the user.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Email address of the user.
	// Email address of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Number) Number of following users.
	// Number of following users.
	FollowersCount *float64 `json:"followersCount,omitempty" tf:"followers_count,omitempty"`

	// (Number) Number of users followed.
	// Number of users followed.
	FollowingCount *float64 `json:"followingCount,omitempty" tf:"following_count,omitempty"`

	// (String) Full name of the user.
	// Full name of the user.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) URL to the user's profile page.
	// URL to the user's profile page.
	HTMLURL *string `json:"htmlUrl,omitempty" tf:"html_url,omitempty"`

	// (Number) Numeric identifier of the user.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Locale of the user.
	// Locale of the user.
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// (String) Time at which the user last logged in.
	// Time at which the user last logged in.
	LastLogin *string `json:"lastLogin,omitempty" tf:"last_login,omitempty"`

	// (String) Location of the user.
	// Location of the user.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Login name of the user.
	// Login name of the user.
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// 1 means no limit.
	// Maximum number of repositories user can create. A value of -1 means no limit.
	MaxRepoCreation *float64 `json:"maxRepoCreation,omitempty" tf:"max_repo_creation,omitempty"`

	// (Boolean) Require user to change password?
	// Require user to change password?
	MustChangePassword *bool `json:"mustChangePassword,omitempty" tf:"must_change_password,omitempty"`

	// (Boolean) Are user logins prohibited?
	// Are user logins prohibited?
	ProhibitLogin *bool `json:"prohibitLogin,omitempty" tf:"prohibit_login,omitempty"`

	// (Boolean) Is the user restricted?
	// Is the user restricted?
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// (Boolean) Send notification to administrators? Changing this forces a new resource to be created.
	// Send notification to administrators? Changing this forces a new resource to be created.
	SendNotify *bool `json:"sendNotify,omitempty" tf:"send_notify,omitempty"`

	// (Number) Numeric identifier of the user's authentication source.
	// Numeric identifier of the user's authentication source.
	SourceID *float64 `json:"sourceId,omitempty" tf:"source_id,omitempty"`

	// (Number) Number of starred repositories.
	// Number of starred repositories.
	StarredReposCount *float64 `json:"starredReposCount,omitempty" tf:"starred_repos_count,omitempty"`

	// (String) Visibility of the user. Possible values are 'public' (default), 'limited', or 'private'.
	// Visibility of the user. Possible values are 'public' (default), 'limited', or 'private'.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) Website of the user.
	// Website of the user.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type UserParameters struct {

	// (Boolean) Is the user active?
	// Is the user active?
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Boolean) Is the user an administrator?
	// Is the user an administrator?
	// +kubebuilder:validation:Optional
	Admin *bool `json:"admin,omitempty" tf:"admin,omitempty"`

	// (Boolean) Allow user to create organizations?
	// Allow user to create organizations?
	// +kubebuilder:validation:Optional
	AllowCreateOrganization *bool `json:"allowCreateOrganization,omitempty" tf:"allow_create_organization,omitempty"`

	// (Boolean) Allow user to create Git hooks?
	// Allow user to create Git hooks?
	// +kubebuilder:validation:Optional
	AllowGitHook *bool `json:"allowGitHook,omitempty" tf:"allow_git_hook,omitempty"`

	// (Boolean) Allow user to import local repositories?
	// Allow user to import local repositories?
	// +kubebuilder:validation:Optional
	AllowImportLocal *bool `json:"allowImportLocal,omitempty" tf:"allow_import_local,omitempty"`

	// (Boolean) Deactivate the user instead of delete?
	// Deactivate the user instead of delete?
	// +kubebuilder:validation:Optional
	DeactivateOnDestroy *bool `json:"deactivateOnDestroy,omitempty" tf:"deactivate_on_destroy,omitempty"`

	// (String) Description of the user.
	// Description of the user.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Email address of the user.
	// Email address of the user.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Full name of the user.
	// Full name of the user.
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Location of the user.
	// Location of the user.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name of the user. Changing this forces a new resource to be created.
	// Name of the user. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String) Login name of the user.
	// Login name of the user.
	// +kubebuilder:validation:Optional
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// 1 means no limit.
	// Maximum number of repositories user can create. A value of -1 means no limit.
	// +kubebuilder:validation:Optional
	MaxRepoCreation *float64 `json:"maxRepoCreation,omitempty" tf:"max_repo_creation,omitempty"`

	// (Boolean) Require user to change password?
	// Require user to change password?
	// +kubebuilder:validation:Optional
	MustChangePassword *bool `json:"mustChangePassword,omitempty" tf:"must_change_password,omitempty"`

	// (String, Sensitive) Password of the user.
	// Password of the user.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v2.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Boolean) Are user logins prohibited?
	// Are user logins prohibited?
	// +kubebuilder:validation:Optional
	ProhibitLogin *bool `json:"prohibitLogin,omitempty" tf:"prohibit_login,omitempty"`

	// (Boolean) Is the user restricted?
	// Is the user restricted?
	// +kubebuilder:validation:Optional
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// (Boolean) Send notification to administrators? Changing this forces a new resource to be created.
	// Send notification to administrators? Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	SendNotify *bool `json:"sendNotify,omitempty" tf:"send_notify,omitempty"`

	// (Number) Numeric identifier of the user's authentication source.
	// Numeric identifier of the user's authentication source.
	// +kubebuilder:validation:Optional
	SourceID *float64 `json:"sourceId,omitempty" tf:"source_id,omitempty"`

	// (String) Visibility of the user. Possible values are 'public' (default), 'limited', or 'private'.
	// Visibility of the user. Possible values are 'public' (default), 'limited', or 'private'.
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) Website of the user.
	// Website of the user.
	// +kubebuilder:validation:Optional
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. Forgejo user resource. Note: Managing users requires administrative privileges!
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,forgejo}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.login) || (has(self.initProvider) && has(self.initProvider.login))",message="spec.forProvider.login is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
