apiVersion: forgejo.forgejo.m.crossplane.io/v1alpha1
kind: SshKey
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: default
spec:
  forProvider:
    key: ${trimspace(tls_private_key.ed25519.public_key_openssh)}
    title: test_key
    user: ${forgejo_user.test.login}

---

apiVersion: forgejo.forgejo.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: default
spec:
  forProvider:
    email: test_user@localhost.localdomain
    passwordSecretRef:
      key: example-key
      name: example-secret
