apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: BranchProtection
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/branchprotection
  labels:
    testing.upbound.io/example-name: defaults
  name: defaults
spec:
  forProvider:
    branchName: main
    repositoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_repo

---

apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/branchprotection
  labels:
    testing.upbound.io/example-name: test_repo
  name: test-repo
spec:
  forProvider:
    autoInit: true
    defaultBranch: custom
    description: Terraform Test Repo owned by user
    issueLabels: Default
    name: personal_test_repo
    private: true
    readme: Default
    template: true
    trustModel: collaborator
    website: http://localhost:3000
