apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: personal_defaults
  name: personal-defaults
spec:
  forProvider:
    name: personal_test_repo_defaults

---

apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: Organization
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: owner
  name: owner
spec:
  forProvider:
    name: test_org

---

apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: owner
  name: owner
spec:
  forProvider:
    email: test_user@localhost.localdomain
    login: test_user
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
