apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: SshKey
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    key: ${trimspace(tls_private_key.ed25519.public_key_openssh)}
    title: test_key
    user: test_user_defaults

---

apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/sshkey
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    email: test_user@localhost.localdomain
    login: test_user
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
