apiVersion: forgejo.forgejo.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/user
  labels:
    testing.upbound.io/example-name: defaults
  name: defaults
spec:
  forProvider:
    email: test_user_defaults@localhost.localdomain
    login: test_user_defaults
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
