apiVersion: forgejo.forgejo.m.crossplane.io/v1alpha1
kind: RepositoryActionSecret
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/repositoryactionsecret
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: default
spec:
  forProvider:
    dataSecretRef:
      key: example-key
      name: example-secret
    name: my_secret
    repositoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: personal

---

apiVersion: forgejo.forgejo.m.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/repositoryactionsecret
  labels:
    testing.upbound.io/example-name: personal
  name: personal
  namespace: default
spec:
  forProvider:
    name: personal_test_repo
