apiVersion: forgejo.forgejo.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/team
  labels:
    testing.upbound.io/example-name: default_team
  name: default-team
  namespace: default
spec:
  forProvider:
    name: org_test_team_defaults
    organizationId: ${forgejo_organization.owner.id}
    unitsMap:
      repo.code: read

---

apiVersion: forgejo.forgejo.m.crossplane.io/v1alpha1
kind: Organization
metadata:
  annotations:
    meta.upbound.io/example-id: forgejo/v1alpha1/team
  labels:
    testing.upbound.io/example-name: owner
  name: owner
  namespace: default
spec:
  forProvider:
    name: test_org
