// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BranchProtectionInitParameters struct {

	// (Set of String) Whitelisted teams for reviewing. Note: This setting is only effective if enable_approvals_whitelist is true.
	// Whitelisted teams for reviewing. **Note**: This setting is only effective if `enable_approvals_whitelist` is `true`.
	// +listType=set
	ApprovalsWhitelistTeams []*string `json:"approvalsWhitelistTeams,omitempty" tf:"approvals_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for reviewing. Note: This setting is only effective if enable_approvals_whitelist is true.
	// Whitelisted users for reviewing. **Note**: This setting is only effective if `enable_approvals_whitelist` is `true`.
	// +listType=set
	ApprovalsWhitelistUsernames []*string `json:"approvalsWhitelistUsernames,omitempty" tf:"approvals_whitelist_usernames,omitempty"`

	// (Boolean) Block merge on official review requests.
	// Block merge on official review requests.
	BlockOnOfficialReviewRequests *bool `json:"blockOnOfficialReviewRequests,omitempty" tf:"block_on_official_review_requests,omitempty"`

	// (Boolean) Block merge if pull request is outdated.
	// Block merge if pull request is outdated.
	BlockOnOutdatedBranch *bool `json:"blockOnOutdatedBranch,omitempty" tf:"block_on_outdated_branch,omitempty"`

	// (Boolean) Block merge on rejected reviews.
	// Block merge on rejected reviews.
	BlockOnRejectedReviews *bool `json:"blockOnRejectedReviews,omitempty" tf:"block_on_rejected_reviews,omitempty"`

	// (String) Name of the branch to protect. Changing this forces a new resource to be created.
	// Name of the branch to protect. Changing this forces a new resource to be created.
	BranchName *string `json:"branchName,omitempty" tf:"branch_name,omitempty"`

	// (Boolean) Dismiss stale approvals.
	// Dismiss stale approvals.
	DismissStaleApprovals *bool `json:"dismissStaleApprovals,omitempty" tf:"dismiss_stale_approvals,omitempty"`

	// (Boolean) Restrict approvals to whitelisted users or teams.
	// Restrict approvals to whitelisted users or teams.
	EnableApprovalsWhitelist *bool `json:"enableApprovalsWhitelist,omitempty" tf:"enable_approvals_whitelist,omitempty"`

	// (Boolean) Restrict merge to whitelisted users or teams.
	// Restrict merge to whitelisted users or teams.
	EnableMergeWhitelist *bool `json:"enableMergeWhitelist,omitempty" tf:"enable_merge_whitelist,omitempty"`

	// (Boolean) Enable push to the branch.
	// Enable push to the branch.
	EnablePush *bool `json:"enablePush,omitempty" tf:"enable_push,omitempty"`

	// (Boolean) Restrict push to whitelisted users or teams. Note: This setting is only effective if enable_push is true.
	// Restrict push to whitelisted users or teams. **Note**: This setting is only effective if `enable_push` is `true`.
	EnablePushWhitelist *bool `json:"enablePushWhitelist,omitempty" tf:"enable_push_whitelist,omitempty"`

	// (Boolean) Enable status check.
	// Enable status check.
	EnableStatusCheck *bool `json:"enableStatusCheck,omitempty" tf:"enable_status_check,omitempty"`

	// (Set of String) Whitelisted teams for merging. Note: This setting is only effective if enable_merge_whitelist is true.
	// Whitelisted teams for merging. **Note**: This setting is only effective if `enable_merge_whitelist` is `true`.
	// +listType=set
	MergeWhitelistTeams []*string `json:"mergeWhitelistTeams,omitempty" tf:"merge_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for merging. Note: This setting is only effective if enable_merge_whitelist is true.
	// Whitelisted users for merging. **Note**: This setting is only effective if `enable_merge_whitelist` is `true`.
	// +listType=set
	MergeWhitelistUsernames []*string `json:"mergeWhitelistUsernames,omitempty" tf:"merge_whitelist_usernames,omitempty"`

	// (String) Protected file patterns (separated using semicolon ';').
	// Protected file patterns (separated using semicolon ';').
	ProtectedFilePatterns *string `json:"protectedFilePatterns,omitempty" tf:"protected_file_patterns,omitempty"`

	// (Boolean) Whitelist deploy keys with write access to push. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelist deploy keys with write access to push. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	PushWhitelistDeployKeys *bool `json:"pushWhitelistDeployKeys,omitempty" tf:"push_whitelist_deploy_keys,omitempty"`

	// (Set of String) Whitelisted teams for pushing. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelisted teams for pushing. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	// +listType=set
	PushWhitelistTeams []*string `json:"pushWhitelistTeams,omitempty" tf:"push_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for pushing. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelisted users for pushing. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	// +listType=set
	PushWhitelistUsernames []*string `json:"pushWhitelistUsernames,omitempty" tf:"push_whitelist_usernames,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (Boolean) Require signed commits.
	// Require signed commits.
	RequireSignedCommits *bool `json:"requireSignedCommits,omitempty" tf:"require_signed_commits,omitempty"`

	// (Number) Number of required approvals.
	// Number of required approvals.
	RequiredApprovals *float64 `json:"requiredApprovals,omitempty" tf:"required_approvals,omitempty"`

	// (List of String) Status check patterns. Note: This setting is only effective if enable_status_check is true.
	// Status check patterns. **Note**: This setting is only effective if `enable_status_check` is `true`.
	StatusCheckContexts []*string `json:"statusCheckContexts,omitempty" tf:"status_check_contexts,omitempty"`

	// (String) Unprotected file patterns (separated using semicolon ';').
	// Unprotected file patterns (separated using semicolon ';').
	UnprotectedFilePatterns *string `json:"unprotectedFilePatterns,omitempty" tf:"unprotected_file_patterns,omitempty"`
}

type BranchProtectionObservation struct {

	// (Set of String) Whitelisted teams for reviewing. Note: This setting is only effective if enable_approvals_whitelist is true.
	// Whitelisted teams for reviewing. **Note**: This setting is only effective if `enable_approvals_whitelist` is `true`.
	// +listType=set
	ApprovalsWhitelistTeams []*string `json:"approvalsWhitelistTeams,omitempty" tf:"approvals_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for reviewing. Note: This setting is only effective if enable_approvals_whitelist is true.
	// Whitelisted users for reviewing. **Note**: This setting is only effective if `enable_approvals_whitelist` is `true`.
	// +listType=set
	ApprovalsWhitelistUsernames []*string `json:"approvalsWhitelistUsernames,omitempty" tf:"approvals_whitelist_usernames,omitempty"`

	// (Boolean) Block merge on official review requests.
	// Block merge on official review requests.
	BlockOnOfficialReviewRequests *bool `json:"blockOnOfficialReviewRequests,omitempty" tf:"block_on_official_review_requests,omitempty"`

	// (Boolean) Block merge if pull request is outdated.
	// Block merge if pull request is outdated.
	BlockOnOutdatedBranch *bool `json:"blockOnOutdatedBranch,omitempty" tf:"block_on_outdated_branch,omitempty"`

	// (Boolean) Block merge on rejected reviews.
	// Block merge on rejected reviews.
	BlockOnRejectedReviews *bool `json:"blockOnRejectedReviews,omitempty" tf:"block_on_rejected_reviews,omitempty"`

	// (String) Name of the branch to protect. Changing this forces a new resource to be created.
	// Name of the branch to protect. Changing this forces a new resource to be created.
	BranchName *string `json:"branchName,omitempty" tf:"branch_name,omitempty"`

	// (Boolean) Dismiss stale approvals.
	// Dismiss stale approvals.
	DismissStaleApprovals *bool `json:"dismissStaleApprovals,omitempty" tf:"dismiss_stale_approvals,omitempty"`

	// (Boolean) Restrict approvals to whitelisted users or teams.
	// Restrict approvals to whitelisted users or teams.
	EnableApprovalsWhitelist *bool `json:"enableApprovalsWhitelist,omitempty" tf:"enable_approvals_whitelist,omitempty"`

	// (Boolean) Restrict merge to whitelisted users or teams.
	// Restrict merge to whitelisted users or teams.
	EnableMergeWhitelist *bool `json:"enableMergeWhitelist,omitempty" tf:"enable_merge_whitelist,omitempty"`

	// (Boolean) Enable push to the branch.
	// Enable push to the branch.
	EnablePush *bool `json:"enablePush,omitempty" tf:"enable_push,omitempty"`

	// (Boolean) Restrict push to whitelisted users or teams. Note: This setting is only effective if enable_push is true.
	// Restrict push to whitelisted users or teams. **Note**: This setting is only effective if `enable_push` is `true`.
	EnablePushWhitelist *bool `json:"enablePushWhitelist,omitempty" tf:"enable_push_whitelist,omitempty"`

	// (Boolean) Enable status check.
	// Enable status check.
	EnableStatusCheck *bool `json:"enableStatusCheck,omitempty" tf:"enable_status_check,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) Whitelisted teams for merging. Note: This setting is only effective if enable_merge_whitelist is true.
	// Whitelisted teams for merging. **Note**: This setting is only effective if `enable_merge_whitelist` is `true`.
	// +listType=set
	MergeWhitelistTeams []*string `json:"mergeWhitelistTeams,omitempty" tf:"merge_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for merging. Note: This setting is only effective if enable_merge_whitelist is true.
	// Whitelisted users for merging. **Note**: This setting is only effective if `enable_merge_whitelist` is `true`.
	// +listType=set
	MergeWhitelistUsernames []*string `json:"mergeWhitelistUsernames,omitempty" tf:"merge_whitelist_usernames,omitempty"`

	// (String) Protected file patterns (separated using semicolon ';').
	// Protected file patterns (separated using semicolon ';').
	ProtectedFilePatterns *string `json:"protectedFilePatterns,omitempty" tf:"protected_file_patterns,omitempty"`

	// (Boolean) Whitelist deploy keys with write access to push. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelist deploy keys with write access to push. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	PushWhitelistDeployKeys *bool `json:"pushWhitelistDeployKeys,omitempty" tf:"push_whitelist_deploy_keys,omitempty"`

	// (Set of String) Whitelisted teams for pushing. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelisted teams for pushing. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	// +listType=set
	PushWhitelistTeams []*string `json:"pushWhitelistTeams,omitempty" tf:"push_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for pushing. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelisted users for pushing. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	// +listType=set
	PushWhitelistUsernames []*string `json:"pushWhitelistUsernames,omitempty" tf:"push_whitelist_usernames,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// (Boolean) Require signed commits.
	// Require signed commits.
	RequireSignedCommits *bool `json:"requireSignedCommits,omitempty" tf:"require_signed_commits,omitempty"`

	// (Number) Number of required approvals.
	// Number of required approvals.
	RequiredApprovals *float64 `json:"requiredApprovals,omitempty" tf:"required_approvals,omitempty"`

	// (List of String) Status check patterns. Note: This setting is only effective if enable_status_check is true.
	// Status check patterns. **Note**: This setting is only effective if `enable_status_check` is `true`.
	StatusCheckContexts []*string `json:"statusCheckContexts,omitempty" tf:"status_check_contexts,omitempty"`

	// (String) Unprotected file patterns (separated using semicolon ';').
	// Unprotected file patterns (separated using semicolon ';').
	UnprotectedFilePatterns *string `json:"unprotectedFilePatterns,omitempty" tf:"unprotected_file_patterns,omitempty"`
}

type BranchProtectionParameters struct {

	// (Set of String) Whitelisted teams for reviewing. Note: This setting is only effective if enable_approvals_whitelist is true.
	// Whitelisted teams for reviewing. **Note**: This setting is only effective if `enable_approvals_whitelist` is `true`.
	// +kubebuilder:validation:Optional
	// +listType=set
	ApprovalsWhitelistTeams []*string `json:"approvalsWhitelistTeams,omitempty" tf:"approvals_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for reviewing. Note: This setting is only effective if enable_approvals_whitelist is true.
	// Whitelisted users for reviewing. **Note**: This setting is only effective if `enable_approvals_whitelist` is `true`.
	// +kubebuilder:validation:Optional
	// +listType=set
	ApprovalsWhitelistUsernames []*string `json:"approvalsWhitelistUsernames,omitempty" tf:"approvals_whitelist_usernames,omitempty"`

	// (Boolean) Block merge on official review requests.
	// Block merge on official review requests.
	// +kubebuilder:validation:Optional
	BlockOnOfficialReviewRequests *bool `json:"blockOnOfficialReviewRequests,omitempty" tf:"block_on_official_review_requests,omitempty"`

	// (Boolean) Block merge if pull request is outdated.
	// Block merge if pull request is outdated.
	// +kubebuilder:validation:Optional
	BlockOnOutdatedBranch *bool `json:"blockOnOutdatedBranch,omitempty" tf:"block_on_outdated_branch,omitempty"`

	// (Boolean) Block merge on rejected reviews.
	// Block merge on rejected reviews.
	// +kubebuilder:validation:Optional
	BlockOnRejectedReviews *bool `json:"blockOnRejectedReviews,omitempty" tf:"block_on_rejected_reviews,omitempty"`

	// (String) Name of the branch to protect. Changing this forces a new resource to be created.
	// Name of the branch to protect. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	BranchName *string `json:"branchName,omitempty" tf:"branch_name,omitempty"`

	// (Boolean) Dismiss stale approvals.
	// Dismiss stale approvals.
	// +kubebuilder:validation:Optional
	DismissStaleApprovals *bool `json:"dismissStaleApprovals,omitempty" tf:"dismiss_stale_approvals,omitempty"`

	// (Boolean) Restrict approvals to whitelisted users or teams.
	// Restrict approvals to whitelisted users or teams.
	// +kubebuilder:validation:Optional
	EnableApprovalsWhitelist *bool `json:"enableApprovalsWhitelist,omitempty" tf:"enable_approvals_whitelist,omitempty"`

	// (Boolean) Restrict merge to whitelisted users or teams.
	// Restrict merge to whitelisted users or teams.
	// +kubebuilder:validation:Optional
	EnableMergeWhitelist *bool `json:"enableMergeWhitelist,omitempty" tf:"enable_merge_whitelist,omitempty"`

	// (Boolean) Enable push to the branch.
	// Enable push to the branch.
	// +kubebuilder:validation:Optional
	EnablePush *bool `json:"enablePush,omitempty" tf:"enable_push,omitempty"`

	// (Boolean) Restrict push to whitelisted users or teams. Note: This setting is only effective if enable_push is true.
	// Restrict push to whitelisted users or teams. **Note**: This setting is only effective if `enable_push` is `true`.
	// +kubebuilder:validation:Optional
	EnablePushWhitelist *bool `json:"enablePushWhitelist,omitempty" tf:"enable_push_whitelist,omitempty"`

	// (Boolean) Enable status check.
	// Enable status check.
	// +kubebuilder:validation:Optional
	EnableStatusCheck *bool `json:"enableStatusCheck,omitempty" tf:"enable_status_check,omitempty"`

	// (Set of String) Whitelisted teams for merging. Note: This setting is only effective if enable_merge_whitelist is true.
	// Whitelisted teams for merging. **Note**: This setting is only effective if `enable_merge_whitelist` is `true`.
	// +kubebuilder:validation:Optional
	// +listType=set
	MergeWhitelistTeams []*string `json:"mergeWhitelistTeams,omitempty" tf:"merge_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for merging. Note: This setting is only effective if enable_merge_whitelist is true.
	// Whitelisted users for merging. **Note**: This setting is only effective if `enable_merge_whitelist` is `true`.
	// +kubebuilder:validation:Optional
	// +listType=set
	MergeWhitelistUsernames []*string `json:"mergeWhitelistUsernames,omitempty" tf:"merge_whitelist_usernames,omitempty"`

	// (String) Protected file patterns (separated using semicolon ';').
	// Protected file patterns (separated using semicolon ';').
	// +kubebuilder:validation:Optional
	ProtectedFilePatterns *string `json:"protectedFilePatterns,omitempty" tf:"protected_file_patterns,omitempty"`

	// (Boolean) Whitelist deploy keys with write access to push. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelist deploy keys with write access to push. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	// +kubebuilder:validation:Optional
	PushWhitelistDeployKeys *bool `json:"pushWhitelistDeployKeys,omitempty" tf:"push_whitelist_deploy_keys,omitempty"`

	// (Set of String) Whitelisted teams for pushing. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelisted teams for pushing. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	// +kubebuilder:validation:Optional
	// +listType=set
	PushWhitelistTeams []*string `json:"pushWhitelistTeams,omitempty" tf:"push_whitelist_teams,omitempty"`

	// (Set of String) Whitelisted users for pushing. Note: This setting is only effective if enable_push_whitelist is true.
	// Whitelisted users for pushing. **Note**: This setting is only effective if `enable_push_whitelist` is `true`.
	// +kubebuilder:validation:Optional
	// +listType=set
	PushWhitelistUsernames []*string `json:"pushWhitelistUsernames,omitempty" tf:"push_whitelist_usernames,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	// +kubebuilder:validation:Optional
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (Boolean) Require signed commits.
	// Require signed commits.
	// +kubebuilder:validation:Optional
	RequireSignedCommits *bool `json:"requireSignedCommits,omitempty" tf:"require_signed_commits,omitempty"`

	// (Number) Number of required approvals.
	// Number of required approvals.
	// +kubebuilder:validation:Optional
	RequiredApprovals *float64 `json:"requiredApprovals,omitempty" tf:"required_approvals,omitempty"`

	// (List of String) Status check patterns. Note: This setting is only effective if enable_status_check is true.
	// Status check patterns. **Note**: This setting is only effective if `enable_status_check` is `true`.
	// +kubebuilder:validation:Optional
	StatusCheckContexts []*string `json:"statusCheckContexts,omitempty" tf:"status_check_contexts,omitempty"`

	// (String) Unprotected file patterns (separated using semicolon ';').
	// Unprotected file patterns (separated using semicolon ';').
	// +kubebuilder:validation:Optional
	UnprotectedFilePatterns *string `json:"unprotectedFilePatterns,omitempty" tf:"unprotected_file_patterns,omitempty"`
}

// BranchProtectionSpec defines the desired state of BranchProtection
type BranchProtectionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BranchProtectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BranchProtectionInitParameters `json:"initProvider,omitempty"`
}

// BranchProtectionStatus defines the observed state of BranchProtection.
type BranchProtectionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BranchProtectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BranchProtection is the Schema for the BranchProtections API. Forgejo branch protection resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type BranchProtection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.branchName) || (has(self.initProvider) && has(self.initProvider.branchName))",message="spec.forProvider.branchName is a required parameter"
	Spec   BranchProtectionSpec   `json:"spec"`
	Status BranchProtectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BranchProtectionList contains a list of BranchProtections
type BranchProtectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BranchProtection `json:"items"`
}

// Repository type metadata.
var (
	BranchProtection_Kind             = "BranchProtection"
	BranchProtection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BranchProtection_Kind}.String()
	BranchProtection_KindAPIVersion   = BranchProtection_Kind + "." + CRDGroupVersion.String()
	BranchProtection_GroupVersionKind = CRDGroupVersion.WithKind(BranchProtection_Kind)
)

func init() {
	SchemeBuilder.Register(&BranchProtection{}, &BranchProtectionList{})
}
