// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CollaboratorInitParameters struct {

	// (String) Repository permissions of the collaborator. Must be one of 'read', 'write', 'admin'.
	// Repository permissions of the collaborator. Must be one of 'read', 'write', 'admin'.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (String) Username of the collaborator. Changing this forces a new resource to be created.
	// Username of the collaborator. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.User
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.NamespacedReference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.NamespacedSelector `json:"userSelector,omitempty" tf:"-"`
}

type CollaboratorObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Repository permissions of the collaborator. Must be one of 'read', 'write', 'admin'.
	// Repository permissions of the collaborator. Must be one of 'read', 'write', 'admin'.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// (String) Username of the collaborator. Changing this forces a new resource to be created.
	// Username of the collaborator. Changing this forces a new resource to be created.
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type CollaboratorParameters struct {

	// (String) Repository permissions of the collaborator. Must be one of 'read', 'write', 'admin'.
	// Repository permissions of the collaborator. Must be one of 'read', 'write', 'admin'.
	// +kubebuilder:validation:Optional
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	// +kubebuilder:validation:Optional
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (String) Username of the collaborator. Changing this forces a new resource to be created.
	// Username of the collaborator. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.User
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.NamespacedReference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in forgejo to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.NamespacedSelector `json:"userSelector,omitempty" tf:"-"`
}

// CollaboratorSpec defines the desired state of Collaborator
type CollaboratorSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CollaboratorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CollaboratorInitParameters `json:"initProvider,omitempty"`
}

// CollaboratorStatus defines the observed state of Collaborator.
type CollaboratorStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CollaboratorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Collaborator is the Schema for the Collaborators API. Forgejo repository collaborator resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type Collaborator struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permission) || (has(self.initProvider) && has(self.initProvider.permission))",message="spec.forProvider.permission is a required parameter"
	Spec   CollaboratorSpec   `json:"spec"`
	Status CollaboratorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CollaboratorList contains a list of Collaborators
type CollaboratorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Collaborator `json:"items"`
}

// Repository type metadata.
var (
	Collaborator_Kind             = "Collaborator"
	Collaborator_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Collaborator_Kind}.String()
	Collaborator_KindAPIVersion   = Collaborator_Kind + "." + CRDGroupVersion.String()
	Collaborator_GroupVersionKind = CRDGroupVersion.WithKind(Collaborator_Kind)
)

func init() {
	SchemeBuilder.Register(&Collaborator{}, &CollaboratorList{})
}
