// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DeployKeyInitParameters struct {

	// (String) Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Boolean) Does the key have only read access? Changing this forces a new resource to be created.
	// Does the key have only read access? Changing this forces a new resource to be created.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (String) Title of the deploy key. Changing this forces a new resource to be created.
	// Title of the deploy key. Changing this forces a new resource to be created.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type DeployKeyObservation struct {

	// (String) Time at which the deploy key was created.
	// Time at which the deploy key was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Fingerprint of the deploy key.
	// Fingerprint of the deploy key.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Number) Numeric identifier of the deploy key.
	// Numeric identifier of the deploy key.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (Boolean) Does the key have only read access? Changing this forces a new resource to be created.
	// Does the key have only read access? Changing this forces a new resource to be created.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// (String) Title of the deploy key. Changing this forces a new resource to be created.
	// Title of the deploy key. Changing this forces a new resource to be created.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (String) URL of the deploy key.
	// URL of the deploy key.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type DeployKeyParameters struct {

	// (String) Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// Armored SSH key. Trailing newlines must be removed (e.g. using trimspace() function). Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Boolean) Does the key have only read access? Changing this forces a new resource to be created.
	// Does the key have only read access? Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	// +kubebuilder:validation:Optional
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (String) Title of the deploy key. Changing this forces a new resource to be created.
	// Title of the deploy key. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

// DeployKeySpec defines the desired state of DeployKey
type DeployKeySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DeployKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeployKeyInitParameters `json:"initProvider,omitempty"`
}

// DeployKeyStatus defines the observed state of DeployKey.
type DeployKeyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DeployKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DeployKey is the Schema for the DeployKeys API. Forgejo repository deploy key resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type DeployKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.readOnly) || (has(self.initProvider) && has(self.initProvider.readOnly))",message="spec.forProvider.readOnly is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	Spec   DeployKeySpec   `json:"spec"`
	Status DeployKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeployKeyList contains a list of DeployKeys
type DeployKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DeployKey `json:"items"`
}

// Repository type metadata.
var (
	DeployKey_Kind             = "DeployKey"
	DeployKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DeployKey_Kind}.String()
	DeployKey_KindAPIVersion   = DeployKey_Kind + "." + CRDGroupVersion.String()
	DeployKey_GroupVersionKind = CRDGroupVersion.WithKind(DeployKey_Kind)
)

func init() {
	SchemeBuilder.Register(&DeployKey{}, &DeployKeyList{})
}
