// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationInitParameters struct {

	// (String) Description of the organization.
	// Description of the organization.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Full name of the organization.
	// Full name of the organization.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Location of the organization.
	// Location of the organization.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name of the organization. Changing this forces a new resource to be created.
	// Name of the organization. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether repository admin can add and remove access for teams. Changing this forces a new resource to be created.
	// Whether repository admin can add and remove access for teams. Changing this forces a new resource to be created.
	RepoAdminChangeTeamAccess *bool `json:"repoAdminChangeTeamAccess,omitempty" tf:"repo_admin_change_team_access,omitempty"`

	// (String) Visibility of the organization. Possible values are 'public' (default), 'limited', or 'private'.
	// Visibility of the organization. Possible values are 'public' (default), 'limited', or 'private'.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) Website of the organization.
	// Website of the organization.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type OrganizationObservation struct {

	// (String) Avatar URL of the organization.
	// Avatar URL of the organization.
	AvatarURL *string `json:"avatarUrl,omitempty" tf:"avatar_url,omitempty"`

	// (String) Description of the organization.
	// Description of the organization.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Full name of the organization.
	// Full name of the organization.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (Number) Numeric identifier of the organization.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Location of the organization.
	// Location of the organization.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name of the organization. Changing this forces a new resource to be created.
	// Name of the organization. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether repository admin can add and remove access for teams. Changing this forces a new resource to be created.
	// Whether repository admin can add and remove access for teams. Changing this forces a new resource to be created.
	RepoAdminChangeTeamAccess *bool `json:"repoAdminChangeTeamAccess,omitempty" tf:"repo_admin_change_team_access,omitempty"`

	// (String) Visibility of the organization. Possible values are 'public' (default), 'limited', or 'private'.
	// Visibility of the organization. Possible values are 'public' (default), 'limited', or 'private'.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) Website of the organization.
	// Website of the organization.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type OrganizationParameters struct {

	// (String) Description of the organization.
	// Description of the organization.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Full name of the organization.
	// Full name of the organization.
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Location of the organization.
	// Location of the organization.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name of the organization. Changing this forces a new resource to be created.
	// Name of the organization. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether repository admin can add and remove access for teams. Changing this forces a new resource to be created.
	// Whether repository admin can add and remove access for teams. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	RepoAdminChangeTeamAccess *bool `json:"repoAdminChangeTeamAccess,omitempty" tf:"repo_admin_change_team_access,omitempty"`

	// (String) Visibility of the organization. Possible values are 'public' (default), 'limited', or 'private'.
	// Visibility of the organization. Possible values are 'public' (default), 'limited', or 'private'.
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) Website of the organization.
	// Website of the organization.
	// +kubebuilder:validation:Optional
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

// OrganizationSpec defines the desired state of Organization
type OrganizationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationInitParameters `json:"initProvider,omitempty"`
}

// OrganizationStatus defines the observed state of Organization.
type OrganizationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Organization is the Schema for the Organizations API. Forgejo organization resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type Organization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationSpec   `json:"spec"`
	Status OrganizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationList contains a list of Organizations
type OrganizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Organization `json:"items"`
}

// Repository type metadata.
var (
	Organization_Kind             = "Organization"
	Organization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Organization_Kind}.String()
	Organization_KindAPIVersion   = Organization_Kind + "." + CRDGroupVersion.String()
	Organization_GroupVersionKind = CRDGroupVersion.WithKind(Organization_Kind)
)

func init() {
	SchemeBuilder.Register(&Organization{}, &OrganizationList{})
}
