// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationActionVariableInitParameters struct {

	// (String) Data of the variable.
	// Data of the variable.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Name of the variable.
	// Name of the variable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type OrganizationActionVariableObservation struct {

	// (String) Data of the variable.
	// Data of the variable.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the variable.
	// Name of the variable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type OrganizationActionVariableParameters struct {

	// (String) Data of the variable.
	// Data of the variable.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Name of the variable.
	// Name of the variable.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Name of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (Number) Numeric identifier of the owning organization. Changing this forces a new resource to be created. Note: One of organization or organization_id must be specified.
	// Numeric identifier of the owning organization. Changing this forces a new resource to be created. **Note**: One of `organization` or `organization_id` must be specified.
	// +kubebuilder:validation:Optional
	OrganizationID *float64 `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

// OrganizationActionVariableSpec defines the desired state of OrganizationActionVariable
type OrganizationActionVariableSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationActionVariableParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationActionVariableInitParameters `json:"initProvider,omitempty"`
}

// OrganizationActionVariableStatus defines the observed state of OrganizationActionVariable.
type OrganizationActionVariableStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationActionVariableObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationActionVariable is the Schema for the OrganizationActionVariables API. Forgejo organization action variable resource. Note: The authenticated user must be a member of the managed organization(s) or have administrative privileges!
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type OrganizationActionVariable struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.data) || (has(self.initProvider) && has(self.initProvider.data))",message="spec.forProvider.data is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationActionVariableSpec   `json:"spec"`
	Status OrganizationActionVariableStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationActionVariableList contains a list of OrganizationActionVariables
type OrganizationActionVariableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationActionVariable `json:"items"`
}

// Repository type metadata.
var (
	OrganizationActionVariable_Kind             = "OrganizationActionVariable"
	OrganizationActionVariable_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationActionVariable_Kind}.String()
	OrganizationActionVariable_KindAPIVersion   = OrganizationActionVariable_Kind + "." + CRDGroupVersion.String()
	OrganizationActionVariable_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationActionVariable_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationActionVariable{}, &OrganizationActionVariableList{})
}
