// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RepositoryActionVariableInitParameters struct {

	// (String) Data of the variable.
	// Data of the variable.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Name of the variable.
	// Name of the variable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`
}

type RepositoryActionVariableObservation struct {

	// (String) Data of the variable.
	// Data of the variable.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the variable.
	// Name of the variable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`
}

type RepositoryActionVariableParameters struct {

	// (String) Data of the variable.
	// Data of the variable.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Name of the variable.
	// Name of the variable.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	// +kubebuilder:validation:Optional
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`
}

// RepositoryActionVariableSpec defines the desired state of RepositoryActionVariable
type RepositoryActionVariableSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RepositoryActionVariableParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryActionVariableInitParameters `json:"initProvider,omitempty"`
}

// RepositoryActionVariableStatus defines the observed state of RepositoryActionVariable.
type RepositoryActionVariableStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RepositoryActionVariableObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryActionVariable is the Schema for the RepositoryActionVariables API. Forgejo repository action variable resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type RepositoryActionVariable struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.data) || (has(self.initProvider) && has(self.initProvider.data))",message="spec.forProvider.data is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RepositoryActionVariableSpec   `json:"spec"`
	Status RepositoryActionVariableStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryActionVariableList contains a list of RepositoryActionVariables
type RepositoryActionVariableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryActionVariable `json:"items"`
}

// Repository type metadata.
var (
	RepositoryActionVariable_Kind             = "RepositoryActionVariable"
	RepositoryActionVariable_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryActionVariable_Kind}.String()
	RepositoryActionVariable_KindAPIVersion   = RepositoryActionVariable_Kind + "." + CRDGroupVersion.String()
	RepositoryActionVariable_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryActionVariable_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryActionVariable{}, &RepositoryActionVariableList{})
}
