// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RepositoryWebhookInitParameters struct {

	// (Boolean) Boolean indicating if the webhook is active.
	// Boolean indicating if the webhook is active.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String, Sensitive) Authorization header to send to the target.
	// Authorization header to send to the target.
	AuthorizationHeaderSecretRef *v2.LocalSecretKeySelector `json:"authorizationHeaderSecretRef,omitempty" tf:"-"`

	// (String) List of allowed branches for push, branch creation and branch deletion events, specified as glob pattern. If empty or *, events for all branches are reported.
	// List of allowed branches for push, branch creation and branch deletion events, specified as glob pattern. If empty or *, events for all branches are reported.
	BranchFilter *string `json:"branchFilter,omitempty" tf:"branch_filter,omitempty"`

	// Map of configuration settings, e.g. "content_type" and "url".
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (Set of String) List of events which trigger the webhook.
	// List of events which trigger the webhook.
	// +listType=set
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (String) Type of webhook. Changing this forces a new resource to be created.
	// Type of webhook. Changing this forces a new resource to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RepositoryWebhookObservation struct {

	// (Boolean) Boolean indicating if the webhook is active.
	// Boolean indicating if the webhook is active.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) List of allowed branches for push, branch creation and branch deletion events, specified as glob pattern. If empty or *, events for all branches are reported.
	// List of allowed branches for push, branch creation and branch deletion events, specified as glob pattern. If empty or *, events for all branches are reported.
	BranchFilter *string `json:"branchFilter,omitempty" tf:"branch_filter,omitempty"`

	// Map of configuration settings, e.g. "content_type" and "url".
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Time at which the webhook was created.
	// Time at which the webhook was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Set of String) List of events which trigger the webhook.
	// List of events which trigger the webhook.
	// +listType=set
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// (String) Type of webhook. Changing this forces a new resource to be created.
	// Type of webhook. Changing this forces a new resource to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Time at which the webhook was updated.
	// Time at which the webhook was updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (Number) Numeric identifier of the webhook.
	// Numeric identifier of the webhook.
	WebhookID *string `json:"webhookId,omitempty" tf:"webhook_id,omitempty"`
}

type RepositoryWebhookParameters struct {

	// (Boolean) Boolean indicating if the webhook is active.
	// Boolean indicating if the webhook is active.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String, Sensitive) Authorization header to send to the target.
	// Authorization header to send to the target.
	// +kubebuilder:validation:Optional
	AuthorizationHeaderSecretRef *v2.LocalSecretKeySelector `json:"authorizationHeaderSecretRef,omitempty" tf:"-"`

	// (String) List of allowed branches for push, branch creation and branch deletion events, specified as glob pattern. If empty or *, events for all branches are reported.
	// List of allowed branches for push, branch creation and branch deletion events, specified as glob pattern. If empty or *, events for all branches are reported.
	// +kubebuilder:validation:Optional
	BranchFilter *string `json:"branchFilter,omitempty" tf:"branch_filter,omitempty"`

	// Map of configuration settings, e.g. "content_type" and "url".
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (Set of String) List of events which trigger the webhook.
	// List of events which trigger the webhook.
	// +kubebuilder:validation:Optional
	// +listType=set
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	// +kubebuilder:validation:Optional
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`

	// (String) Type of webhook. Changing this forces a new resource to be created.
	// Type of webhook. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// RepositoryWebhookSpec defines the desired state of RepositoryWebhook
type RepositoryWebhookSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RepositoryWebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryWebhookInitParameters `json:"initProvider,omitempty"`
}

// RepositoryWebhookStatus defines the observed state of RepositoryWebhook.
type RepositoryWebhookStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RepositoryWebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryWebhook is the Schema for the RepositoryWebhooks API. Forgejo repository webhook resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type RepositoryWebhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.config) || (has(self.initProvider) && has(self.initProvider.config))",message="spec.forProvider.config is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   RepositoryWebhookSpec   `json:"spec"`
	Status RepositoryWebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryWebhookList contains a list of RepositoryWebhooks
type RepositoryWebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryWebhook `json:"items"`
}

// Repository type metadata.
var (
	RepositoryWebhook_Kind             = "RepositoryWebhook"
	RepositoryWebhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryWebhook_Kind}.String()
	RepositoryWebhook_KindAPIVersion   = RepositoryWebhook_Kind + "." + CRDGroupVersion.String()
	RepositoryWebhook_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryWebhook_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryWebhook{}, &RepositoryWebhookList{})
}
