// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RepositoryActionSecretInitParameters struct {

	// (String, Sensitive) Data of the secret.
	// Data of the secret.
	DataSecretRef v2.LocalSecretKeySelector `json:"dataSecretRef" tf:"-"`

	// (String) Name of the secret. Changing this forces a new resource to be created.
	// Name of the secret. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`
}

type RepositoryActionSecretObservation struct {

	// (String) Time at which the secret was created.
	// Time at which the secret was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the secret. Changing this forces a new resource to be created.
	// Name of the secret. Changing this forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`
}

type RepositoryActionSecretParameters struct {

	// (String, Sensitive) Data of the secret.
	// Data of the secret.
	// +kubebuilder:validation:Optional
	DataSecretRef v2.LocalSecretKeySelector `json:"dataSecretRef" tf:"-"`

	// (String) Name of the secret. Changing this forces a new resource to be created.
	// Name of the secret. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Numeric identifier of the repository. Changing this forces a new resource to be created.
	// Numeric identifier of the repository. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-forgejo/apis/namespaced/forgejo/v1alpha1.Repository
	// +kubebuilder:validation:Optional
	RepositoryID *float64 `json:"repositoryId,omitempty" tf:"repository_id,omitempty"`

	// Reference to a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDRef *v2.NamespacedReference `json:"repositoryIdRef,omitempty" tf:"-"`

	// Selector for a Repository in forgejo to populate repositoryId.
	// +kubebuilder:validation:Optional
	RepositoryIDSelector *v2.NamespacedSelector `json:"repositoryIdSelector,omitempty" tf:"-"`
}

// RepositoryActionSecretSpec defines the desired state of RepositoryActionSecret
type RepositoryActionSecretSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RepositoryActionSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryActionSecretInitParameters `json:"initProvider,omitempty"`
}

// RepositoryActionSecretStatus defines the observed state of RepositoryActionSecret.
type RepositoryActionSecretStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RepositoryActionSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryActionSecret is the Schema for the RepositoryActionSecrets API. Forgejo repository action secret resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,forgejo}
type RepositoryActionSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataSecretRef)",message="spec.forProvider.dataSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RepositoryActionSecretSpec   `json:"spec"`
	Status RepositoryActionSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryActionSecretList contains a list of RepositoryActionSecrets
type RepositoryActionSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryActionSecret `json:"items"`
}

// Repository type metadata.
var (
	RepositoryActionSecret_Kind             = "RepositoryActionSecret"
	RepositoryActionSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryActionSecret_Kind}.String()
	RepositoryActionSecret_KindAPIVersion   = RepositoryActionSecret_Kind + "." + CRDGroupVersion.String()
	RepositoryActionSecret_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryActionSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryActionSecret{}, &RepositoryActionSecretList{})
}
